/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as PolytomicApi from "../../api";
import * as core from "../../core";
export declare const LabelLabel: core.serialization.Schema<serializers.LabelLabel.Raw, PolytomicApi.LabelLabel>;
export declare namespace LabelLabel {
    type Raw = Record<string, unknown>;
}
