/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as PolytomicApi from "../../api";
import * as core from "../../core";
export declare const V2EventTypesEnvelope: core.serialization.ObjectSchema<serializers.V2EventTypesEnvelope.Raw, PolytomicApi.V2EventTypesEnvelope>;
export declare namespace V2EventTypesEnvelope {
    interface Raw {
        data?: string[] | null;
    }
}
