/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as PolytomicApi from "../../api";
import * as core from "../../core";
export declare const V2Filter: core.serialization.ObjectSchema<serializers.V2Filter.Raw, PolytomicApi.V2Filter>;
export declare namespace V2Filter {
    interface Raw {
        field_id: string;
        field_type: string;
        function: string;
        label?: string | null;
        value?: unknown | null;
    }
}
