/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as PolytomicApi from "../../api";
import * as core from "../../core";
export declare const V2GetConnectionMetaEnvelope: core.serialization.ObjectSchema<serializers.V2GetConnectionMetaEnvelope.Raw, PolytomicApi.V2GetConnectionMetaEnvelope>;
export declare namespace V2GetConnectionMetaEnvelope {
    interface Raw {
        data?: serializers.V2ConnectionMetaResponse.Raw | null;
    }
}
