/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as PolytomicApi from "../../api";
import * as core from "../../core";
export declare const V2OrganizationsEnvelope: core.serialization.ObjectSchema<serializers.V2OrganizationsEnvelope.Raw, PolytomicApi.V2OrganizationsEnvelope>;
export declare namespace V2OrganizationsEnvelope {
    interface Raw {
        data?: serializers.V2Organization.Raw[] | null;
    }
}
