/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as PolytomicApi from "../../api";
import * as core from "../../core";
export declare const V2Target: core.serialization.ObjectSchema<serializers.V2Target.Raw, PolytomicApi.V2Target>;
export declare namespace V2Target {
    interface Raw {
        configuration?: Record<string, unknown> | null;
        connection_id: string;
        filter_logic?: string | null;
        new_name?: string | null;
        object: string;
        search_values?: Record<string, unknown> | null;
    }
}
