/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as PolytomicApi from "../../api";
import * as core from "../../core";
export declare const V2User: core.serialization.ObjectSchema<serializers.V2User.Raw, PolytomicApi.V2User>;
export declare namespace V2User {
    interface Raw {
        email?: string | null;
        id?: string | null;
        organization_id?: string | null;
        role?: string | null;
    }
}
