/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as PolytomicApi from "../../api";
import * as core from "../../core";
export declare const V3BulkSchema: core.serialization.ObjectSchema<serializers.V3BulkSchema.Raw, PolytomicApi.V3BulkSchema>;
export declare namespace V3BulkSchema {
    interface Raw {
        enabled?: boolean | null;
        fields?: serializers.V3BulkField.Raw[] | null;
        id?: string | null;
        partition_key?: string | null;
    }
}
