/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface V2ConnectionType {
    envConfig?: Record<string, unknown>;
    id?: string;
    name?: string;
    useOauth?: boolean;
}
