/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as PolytomicApi from "..";
export interface V2CreateConnectionResponseSchema {
    /** Code to enter in order to complete connection authentication. */
    authCode?: string;
    /** URL to visit to complete connection authentication. */
    authUrl?: string;
    configuration?: Record<string, unknown>;
    id?: string;
    name?: string;
    organizationId?: string;
    policies?: string[];
    status?: string;
    statusError?: string;
    type?: PolytomicApi.V2ConnectionTypeSchema;
}
