/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as PolytomicApi from "..";
export interface V2SyncStatusResponse {
    currentExecution?: PolytomicApi.V2GetExecutionResponseSchema;
    lastExecution?: PolytomicApi.V2GetExecutionResponseSchema;
    nextExecutionTime?: Date;
}
