/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as PolytomicApi from "..";
export interface V3BulkSyncStatusResponse {
    currentExecution?: PolytomicApi.V3BulkSyncExecution;
    lastExecution?: PolytomicApi.V3BulkSyncExecution;
    nextExecutionTime?: Date;
}
