// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient";
import * as core from "../../../../core";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers";
import { toJson } from "../../../../core/json";
import * as environments from "../../../../environments";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError";
import * as errors from "../../../../errors/index";
import * as Polytomic from "../../../index";
import { ExecutionsClient } from "../resources/executions/client/Client";
import { TargetsClient } from "../resources/targets/client/Client";

export declare namespace ModelSyncClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class ModelSyncClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<ModelSyncClient.Options>;
    protected _targets: TargetsClient | undefined;
    protected _executions: ExecutionsClient | undefined;

    constructor(options: ModelSyncClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get targets(): TargetsClient {
        return (this._targets ??= new TargetsClient(this._options));
    }

    public get executions(): ExecutionsClient {
        return (this._executions ??= new ExecutionsClient(this._options));
    }

    /**
     * @param {string} id
     * @param {Polytomic.ModelSyncGetSourceRequest} request
     * @param {ModelSyncClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Polytomic.BadRequestError}
     * @throws {@link Polytomic.UnauthorizedError}
     * @throws {@link Polytomic.ForbiddenError}
     * @throws {@link Polytomic.NotFoundError}
     * @throws {@link Polytomic.InternalServerError}
     *
     * @example
     *     await client.modelSync.getSource("248df4b7-aa70-47b8-a036-33ac447e668d")
     */
    public getSource(
        id: string,
        request: Polytomic.ModelSyncGetSourceRequest = {},
        requestOptions?: ModelSyncClient.RequestOptions,
    ): core.HttpResponsePromise<Polytomic.GetModelSyncSourceMetaEnvelope> {
        return core.HttpResponsePromise.fromPromise(this.__getSource(id, request, requestOptions));
    }

    private async __getSource(
        id: string,
        request: Polytomic.ModelSyncGetSourceRequest = {},
        requestOptions?: ModelSyncClient.RequestOptions,
    ): Promise<core.WithRawResponse<Polytomic.GetModelSyncSourceMetaEnvelope>> {
        const { params } = request;
        const _queryParams: Record<string, unknown> = {
            params: params != null ? toJson(params) : undefined,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "X-Polytomic-Version": requestOptions?.version ?? this._options?.version }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PolytomicEnvironment.Default,
                `api/connections/${core.url.encodePathParam(id)}/modelsync/source`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as Polytomic.GetModelSyncSourceMetaEnvelope,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Polytomic.BadRequestError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                case 401:
                    throw new Polytomic.UnauthorizedError(
                        _response.error.body as Polytomic.RestErrResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Polytomic.ForbiddenError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Polytomic.NotFoundError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Polytomic.InternalServerError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.PolytomicError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/api/connections/{id}/modelsync/source",
        );
    }

    /**
     * @param {string} id
     * @param {Polytomic.ModelSyncGetSourceFieldsRequest} request
     * @param {ModelSyncClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Polytomic.BadRequestError}
     * @throws {@link Polytomic.UnauthorizedError}
     * @throws {@link Polytomic.ForbiddenError}
     * @throws {@link Polytomic.NotFoundError}
     * @throws {@link Polytomic.InternalServerError}
     *
     * @example
     *     await client.modelSync.getSourceFields("248df4b7-aa70-47b8-a036-33ac447e668d")
     */
    public getSourceFields(
        id: string,
        request: Polytomic.ModelSyncGetSourceFieldsRequest = {},
        requestOptions?: ModelSyncClient.RequestOptions,
    ): core.HttpResponsePromise<Polytomic.ModelFieldResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getSourceFields(id, request, requestOptions));
    }

    private async __getSourceFields(
        id: string,
        request: Polytomic.ModelSyncGetSourceFieldsRequest = {},
        requestOptions?: ModelSyncClient.RequestOptions,
    ): Promise<core.WithRawResponse<Polytomic.ModelFieldResponse>> {
        const { params } = request;
        const _queryParams: Record<string, unknown> = {
            params: params != null ? toJson(params) : undefined,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "X-Polytomic-Version": requestOptions?.version ?? this._options?.version }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PolytomicEnvironment.Default,
                `api/connections/${core.url.encodePathParam(id)}/modelsync/source/fields`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Polytomic.ModelFieldResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Polytomic.BadRequestError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                case 401:
                    throw new Polytomic.UnauthorizedError(
                        _response.error.body as Polytomic.RestErrResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Polytomic.ForbiddenError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Polytomic.NotFoundError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Polytomic.InternalServerError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.PolytomicError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/api/connections/{id}/modelsync/source/fields",
        );
    }

    /**
     * @param {Polytomic.ModelSyncListRequest} request
     * @param {ModelSyncClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Polytomic.BadRequestError}
     * @throws {@link Polytomic.UnauthorizedError}
     * @throws {@link Polytomic.NotFoundError}
     * @throws {@link Polytomic.InternalServerError}
     *
     * @example
     *     await client.modelSync.list({
     *         active: true,
     *         mode: "create",
     *         target_connection_id: "0b155265-c537-44c9-9359-a3ceb468a4da"
     *     })
     */
    public list(
        request: Polytomic.ModelSyncListRequest = {},
        requestOptions?: ModelSyncClient.RequestOptions,
    ): core.HttpResponsePromise<Polytomic.ListModelSyncResponseEnvelope> {
        return core.HttpResponsePromise.fromPromise(this.__list(request, requestOptions));
    }

    private async __list(
        request: Polytomic.ModelSyncListRequest = {},
        requestOptions?: ModelSyncClient.RequestOptions,
    ): Promise<core.WithRawResponse<Polytomic.ListModelSyncResponseEnvelope>> {
        const { active, mode, target_connection_id: targetConnectionId } = request;
        const _queryParams: Record<string, unknown> = {
            active,
            mode: mode != null ? mode : undefined,
            target_connection_id: targetConnectionId,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "X-Polytomic-Version": requestOptions?.version ?? this._options?.version }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PolytomicEnvironment.Default,
                "api/syncs",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as Polytomic.ListModelSyncResponseEnvelope,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Polytomic.BadRequestError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                case 401:
                    throw new Polytomic.UnauthorizedError(
                        _response.error.body as Polytomic.RestErrResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Polytomic.NotFoundError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Polytomic.InternalServerError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.PolytomicError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/api/syncs");
    }

    /**
     * Create a new sync from one or more models to a destination.
     *
     * All of the functionality described in [the product
     * documentation](https://docs.polytomic.com/docs/sync-destinations) is
     * configurable via the API.
     *
     * Guides:
     *
     * - [Model sync (Reverse ETL) from Snowflake query to Salesforce](https://apidocs.polytomic.com/2024-02-08/guides/code-examples/model-sync-reverse-etl-from-snowflake-query-to-salesforce)
     * - [Joined model sync from Postgres, Airtable, and Stripe to Hubspot](https://apidocs.polytomic.com/2024-02-08/guides/code-examples/joined-model-sync-from-postgres-airtable-and-stripe-to-hubspot)
     *
     * ## Targets (Destinations)
     *
     * Polytomic refers to a model sync's destination as the "target object", or
     * target. Target objects are identified by a connection ID and an object ID. You
     * can retrieve a list of all target objects for a connection using the [Get Target
     * Objects](./targets/list) endpoint.
     *
     * The `target` object in the request specifies information about the sync destination.
     *
     * ```json
     * "target": {
     *     "connection_id": "248df4b7-aa70-47b8-a036-33ac447e668d",
     *     "object": "Users",
     * },
     * ```
     *
     * Some connections support additional configuration for targets. For example,
     * [Salesforce
     * connections](https://apidocs.polytomic.com/2024-02-08/guides/configuring-your-connections/connections/salesforce#target)
     * support optionally specifying the ingestion API to use. The target specific
     * options are passed as `configuration`; consult the [integration
     * guides](https://apidocs.polytomic.com/2024-02-08/guides/configuring-your-connections/overview)
     * for details about specific connection configurations.
     *
     * ### Creating a new target
     *
     * Some integrations support creating a new target when creating a model sync. For
     * example, an ad audience or database table.
     *
     * When creating a new target, `object` is omitted and `create` is specified
     * instead. The `create` property is an object containing integration specific
     * configuration for the new target.
     *
     * ```json
     * "target": {
     *     "connection_id": "248df4b7-aa70-47b8-a036-33ac447e668d",
     *     "create": {
     *         "name": "New audience",
     *         "type": "user_audience"
     *     }
     * },
     * ```
     *
     * The [Get Target List](./targets/list) endpoint returns information about whether
     * a connection supports target creation.
     *
     * @param {Polytomic.CreateModelSyncRequest} request
     * @param {ModelSyncClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Polytomic.BadRequestError}
     * @throws {@link Polytomic.UnauthorizedError}
     * @throws {@link Polytomic.ForbiddenError}
     * @throws {@link Polytomic.UnprocessableEntityError}
     * @throws {@link Polytomic.InternalServerError}
     *
     * @example
     *     await client.modelSync.create({
     *         fields: [{
     *                 target: "name"
     *             }],
     *         mode: "create",
     *         name: "Users Sync",
     *         schedule: {},
     *         target: {
     *             connection_id: "248df4b7-aa70-47b8-a036-33ac447e668d"
     *         }
     *     })
     */
    public create(
        request: Polytomic.CreateModelSyncRequest,
        requestOptions?: ModelSyncClient.RequestOptions,
    ): core.HttpResponsePromise<Polytomic.ModelSyncResponseEnvelope> {
        return core.HttpResponsePromise.fromPromise(this.__create(request, requestOptions));
    }

    private async __create(
        request: Polytomic.CreateModelSyncRequest,
        requestOptions?: ModelSyncClient.RequestOptions,
    ): Promise<core.WithRawResponse<Polytomic.ModelSyncResponseEnvelope>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "X-Polytomic-Version": requestOptions?.version ?? this._options?.version }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PolytomicEnvironment.Default,
                "api/syncs",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Polytomic.ModelSyncResponseEnvelope, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Polytomic.BadRequestError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                case 401:
                    throw new Polytomic.UnauthorizedError(
                        _response.error.body as Polytomic.RestErrResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Polytomic.ForbiddenError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                case 422:
                    throw new Polytomic.UnprocessableEntityError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Polytomic.InternalServerError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.PolytomicError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/api/syncs");
    }

    /**
     * @param {ModelSyncClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Polytomic.UnauthorizedError}
     * @throws {@link Polytomic.InternalServerError}
     *
     * @example
     *     await client.modelSync.getScheduleOptions()
     */
    public getScheduleOptions(
        requestOptions?: ModelSyncClient.RequestOptions,
    ): core.HttpResponsePromise<Polytomic.ScheduleOptionResponseEnvelope> {
        return core.HttpResponsePromise.fromPromise(this.__getScheduleOptions(requestOptions));
    }

    private async __getScheduleOptions(
        requestOptions?: ModelSyncClient.RequestOptions,
    ): Promise<core.WithRawResponse<Polytomic.ScheduleOptionResponseEnvelope>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "X-Polytomic-Version": requestOptions?.version ?? this._options?.version }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PolytomicEnvironment.Default,
                "api/syncs/schedules",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as Polytomic.ScheduleOptionResponseEnvelope,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Polytomic.UnauthorizedError(
                        _response.error.body as Polytomic.RestErrResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Polytomic.InternalServerError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.PolytomicError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/api/syncs/schedules");
    }

    /**
     * @param {string} id
     * @param {ModelSyncClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Polytomic.UnauthorizedError}
     * @throws {@link Polytomic.NotFoundError}
     * @throws {@link Polytomic.InternalServerError}
     *
     * @example
     *     await client.modelSync.get("248df4b7-aa70-47b8-a036-33ac447e668d")
     */
    public get(
        id: string,
        requestOptions?: ModelSyncClient.RequestOptions,
    ): core.HttpResponsePromise<Polytomic.ModelSyncResponseEnvelope> {
        return core.HttpResponsePromise.fromPromise(this.__get(id, requestOptions));
    }

    private async __get(
        id: string,
        requestOptions?: ModelSyncClient.RequestOptions,
    ): Promise<core.WithRawResponse<Polytomic.ModelSyncResponseEnvelope>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "X-Polytomic-Version": requestOptions?.version ?? this._options?.version }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PolytomicEnvironment.Default,
                `api/syncs/${core.url.encodePathParam(id)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Polytomic.ModelSyncResponseEnvelope, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Polytomic.UnauthorizedError(
                        _response.error.body as Polytomic.RestErrResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Polytomic.NotFoundError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Polytomic.InternalServerError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.PolytomicError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/api/syncs/{id}");
    }

    /**
     * @param {string} id
     * @param {Polytomic.UpdateModelSyncRequest} request
     * @param {ModelSyncClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Polytomic.BadRequestError}
     * @throws {@link Polytomic.UnauthorizedError}
     * @throws {@link Polytomic.ForbiddenError}
     * @throws {@link Polytomic.NotFoundError}
     * @throws {@link Polytomic.UnprocessableEntityError}
     * @throws {@link Polytomic.InternalServerError}
     *
     * @example
     *     await client.modelSync.update("248df4b7-aa70-47b8-a036-33ac447e668d", {
     *         fields: [{
     *                 target: "name"
     *             }],
     *         mode: "create",
     *         name: "Users Sync",
     *         schedule: {},
     *         target: {
     *             connection_id: "248df4b7-aa70-47b8-a036-33ac447e668d"
     *         }
     *     })
     */
    public update(
        id: string,
        request: Polytomic.UpdateModelSyncRequest,
        requestOptions?: ModelSyncClient.RequestOptions,
    ): core.HttpResponsePromise<Polytomic.ModelSyncResponseEnvelope> {
        return core.HttpResponsePromise.fromPromise(this.__update(id, request, requestOptions));
    }

    private async __update(
        id: string,
        request: Polytomic.UpdateModelSyncRequest,
        requestOptions?: ModelSyncClient.RequestOptions,
    ): Promise<core.WithRawResponse<Polytomic.ModelSyncResponseEnvelope>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "X-Polytomic-Version": requestOptions?.version ?? this._options?.version }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PolytomicEnvironment.Default,
                `api/syncs/${core.url.encodePathParam(id)}`,
            ),
            method: "PUT",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Polytomic.ModelSyncResponseEnvelope, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Polytomic.BadRequestError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                case 401:
                    throw new Polytomic.UnauthorizedError(
                        _response.error.body as Polytomic.RestErrResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Polytomic.ForbiddenError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Polytomic.NotFoundError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                case 422:
                    throw new Polytomic.UnprocessableEntityError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Polytomic.InternalServerError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.PolytomicError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "PUT", "/api/syncs/{id}");
    }

    /**
     * @param {string} id
     * @param {ModelSyncClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Polytomic.UnauthorizedError}
     * @throws {@link Polytomic.ForbiddenError}
     * @throws {@link Polytomic.NotFoundError}
     * @throws {@link Polytomic.ConflictError}
     * @throws {@link Polytomic.InternalServerError}
     *
     * @example
     *     await client.modelSync.remove("248df4b7-aa70-47b8-a036-33ac447e668d")
     */
    public remove(id: string, requestOptions?: ModelSyncClient.RequestOptions): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__remove(id, requestOptions));
    }

    private async __remove(
        id: string,
        requestOptions?: ModelSyncClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "X-Polytomic-Version": requestOptions?.version ?? this._options?.version }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PolytomicEnvironment.Default,
                `api/syncs/${core.url.encodePathParam(id)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Polytomic.UnauthorizedError(
                        _response.error.body as Polytomic.RestErrResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Polytomic.ForbiddenError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Polytomic.NotFoundError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                case 409:
                    throw new Polytomic.ConflictError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Polytomic.InternalServerError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.PolytomicError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "DELETE", "/api/syncs/{id}");
    }

    /**
     * @param {string} id
     * @param {Polytomic.ActivateSyncInput} request
     * @param {ModelSyncClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Polytomic.UnauthorizedError}
     * @throws {@link Polytomic.ForbiddenError}
     * @throws {@link Polytomic.NotFoundError}
     * @throws {@link Polytomic.InternalServerError}
     *
     * @example
     *     await client.modelSync.activate("248df4b7-aa70-47b8-a036-33ac447e668d", {
     *         active: true
     *     })
     */
    public activate(
        id: string,
        request: Polytomic.ActivateSyncInput,
        requestOptions?: ModelSyncClient.RequestOptions,
    ): core.HttpResponsePromise<Polytomic.ActivateSyncEnvelope> {
        return core.HttpResponsePromise.fromPromise(this.__activate(id, request, requestOptions));
    }

    private async __activate(
        id: string,
        request: Polytomic.ActivateSyncInput,
        requestOptions?: ModelSyncClient.RequestOptions,
    ): Promise<core.WithRawResponse<Polytomic.ActivateSyncEnvelope>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "X-Polytomic-Version": requestOptions?.version ?? this._options?.version }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PolytomicEnvironment.Default,
                `api/syncs/${core.url.encodePathParam(id)}/activate`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Polytomic.ActivateSyncEnvelope, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Polytomic.UnauthorizedError(
                        _response.error.body as Polytomic.RestErrResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Polytomic.ForbiddenError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Polytomic.NotFoundError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Polytomic.InternalServerError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.PolytomicError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/api/syncs/{id}/activate");
    }

    /**
     * @param {string} id - The active execution of this sync ID will be cancelled.
     * @param {ModelSyncClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Polytomic.UnauthorizedError}
     * @throws {@link Polytomic.ForbiddenError}
     * @throws {@link Polytomic.NotFoundError}
     * @throws {@link Polytomic.InternalServerError}
     *
     * @example
     *     await client.modelSync.cancel("248df4b7-aa70-47b8-a036-33ac447e668d")
     */
    public cancel(
        id: string,
        requestOptions?: ModelSyncClient.RequestOptions,
    ): core.HttpResponsePromise<Polytomic.CancelModelSyncResponseEnvelope> {
        return core.HttpResponsePromise.fromPromise(this.__cancel(id, requestOptions));
    }

    private async __cancel(
        id: string,
        requestOptions?: ModelSyncClient.RequestOptions,
    ): Promise<core.WithRawResponse<Polytomic.CancelModelSyncResponseEnvelope>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "X-Polytomic-Version": requestOptions?.version ?? this._options?.version }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PolytomicEnvironment.Default,
                `api/syncs/${core.url.encodePathParam(id)}/cancel`,
            ),
            method: "POST",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as Polytomic.CancelModelSyncResponseEnvelope,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Polytomic.UnauthorizedError(
                        _response.error.body as Polytomic.RestErrResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Polytomic.ForbiddenError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Polytomic.NotFoundError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Polytomic.InternalServerError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.PolytomicError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/api/syncs/{id}/cancel");
    }

    /**
     * > 🚧 Force full resync
     * >
     * > Use caution when setting the `resync` parameter to `true`. This will force a full resync of the data from the source system. This can be a time-consuming operation and may impact the performance of the source system. It is recommended to only use this option when necessary.
     *
     * @param {string} id
     * @param {Polytomic.StartModelSyncRequest} request
     * @param {ModelSyncClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Polytomic.BadRequestError}
     * @throws {@link Polytomic.UnauthorizedError}
     * @throws {@link Polytomic.ForbiddenError}
     * @throws {@link Polytomic.NotFoundError}
     * @throws {@link Polytomic.ConflictError}
     * @throws {@link Polytomic.InternalServerError}
     *
     * @example
     *     await client.modelSync.start("248df4b7-aa70-47b8-a036-33ac447e668d")
     */
    public start(
        id: string,
        request: Polytomic.StartModelSyncRequest = {},
        requestOptions?: ModelSyncClient.RequestOptions,
    ): core.HttpResponsePromise<Polytomic.StartModelSyncResponseEnvelope> {
        return core.HttpResponsePromise.fromPromise(this.__start(id, request, requestOptions));
    }

    private async __start(
        id: string,
        request: Polytomic.StartModelSyncRequest = {},
        requestOptions?: ModelSyncClient.RequestOptions,
    ): Promise<core.WithRawResponse<Polytomic.StartModelSyncResponseEnvelope>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "X-Polytomic-Version": requestOptions?.version ?? this._options?.version }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PolytomicEnvironment.Default,
                `api/syncs/${core.url.encodePathParam(id)}/executions`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as Polytomic.StartModelSyncResponseEnvelope,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Polytomic.BadRequestError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                case 401:
                    throw new Polytomic.UnauthorizedError(
                        _response.error.body as Polytomic.RestErrResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Polytomic.ForbiddenError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Polytomic.NotFoundError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                case 409:
                    throw new Polytomic.ConflictError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Polytomic.InternalServerError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.PolytomicError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/api/syncs/{id}/executions");
    }

    /**
     * @param {string} id
     * @param {ModelSyncClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Polytomic.UnauthorizedError}
     * @throws {@link Polytomic.NotFoundError}
     * @throws {@link Polytomic.InternalServerError}
     *
     * @example
     *     await client.modelSync.getStatus("248df4b7-aa70-47b8-a036-33ac447e668d")
     */
    public getStatus(
        id: string,
        requestOptions?: ModelSyncClient.RequestOptions,
    ): core.HttpResponsePromise<Polytomic.SyncStatusEnvelope> {
        return core.HttpResponsePromise.fromPromise(this.__getStatus(id, requestOptions));
    }

    private async __getStatus(
        id: string,
        requestOptions?: ModelSyncClient.RequestOptions,
    ): Promise<core.WithRawResponse<Polytomic.SyncStatusEnvelope>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "X-Polytomic-Version": requestOptions?.version ?? this._options?.version }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PolytomicEnvironment.Default,
                `api/syncs/${core.url.encodePathParam(id)}/status`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Polytomic.SyncStatusEnvelope, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Polytomic.UnauthorizedError(
                        _response.error.body as Polytomic.RestErrResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Polytomic.NotFoundError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Polytomic.InternalServerError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.PolytomicError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/api/syncs/{id}/status");
    }
}
