"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.V2TargetRequest = exports.V2ModelFieldsRequest = exports.V2UpdateConnectionRequestSchema = exports.V3ConnectCardRequest = exports.V2CreateConnectionRequestSchema = void 0;
var V2CreateConnectionRequestSchema_1 = require("./V2CreateConnectionRequestSchema");
Object.defineProperty(exports, "V2CreateConnectionRequestSchema", { enumerable: true, get: function () { return V2CreateConnectionRequestSchema_1.V2CreateConnectionRequestSchema; } });
var V3ConnectCardRequest_1 = require("./V3ConnectCardRequest");
Object.defineProperty(exports, "V3ConnectCardRequest", { enumerable: true, get: function () { return V3ConnectCardRequest_1.V3ConnectCardRequest; } });
var V2UpdateConnectionRequestSchema_1 = require("./V2UpdateConnectionRequestSchema");
Object.defineProperty(exports, "V2UpdateConnectionRequestSchema", { enumerable: true, get: function () { return V2UpdateConnectionRequestSchema_1.V2UpdateConnectionRequestSchema; } });
var V2ModelFieldsRequest_1 = require("./V2ModelFieldsRequest");
Object.defineProperty(exports, "V2ModelFieldsRequest", { enumerable: true, get: function () { return V2ModelFieldsRequest_1.V2ModelFieldsRequest; } });
var V2TargetRequest_1 = require("./V2TargetRequest");
Object.defineProperty(exports, "V2TargetRequest", { enumerable: true, get: function () { return V2TargetRequest_1.V2TargetRequest; } });
