// This file was auto-generated by Fern from our API Definition.

import type * as core from "../../core";
import * as errors from "../../errors/index";
import type * as Polytomic from "../index";

export class UnauthorizedError extends errors.PolytomicError {
    constructor(body: Polytomic.ApiError, rawResponse?: core.RawResponse) {
        super({
            message: "UnauthorizedError",
            statusCode: 401,
            body: body,
            rawResponse: rawResponse,
        });
        Object.setPrototypeOf(this, new.target.prototype);
        if (Error.captureStackTrace) {
            Error.captureStackTrace(this, this.constructor);
        }

        this.name = this.constructor.name;
    }
}
