"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.V2UpdateRoleRequest = exports.V2CreateRoleRequest = exports.V2UpdatePolicyRequest = exports.V2CreatePolicyRequest = void 0;
var V2CreatePolicyRequest_1 = require("./V2CreatePolicyRequest");
Object.defineProperty(exports, "V2CreatePolicyRequest", { enumerable: true, get: function () { return V2CreatePolicyRequest_1.V2CreatePolicyRequest; } });
var V2UpdatePolicyRequest_1 = require("./V2UpdatePolicyRequest");
Object.defineProperty(exports, "V2UpdatePolicyRequest", { enumerable: true, get: function () { return V2UpdatePolicyRequest_1.V2UpdatePolicyRequest; } });
var V2CreateRoleRequest_1 = require("./V2CreateRoleRequest");
Object.defineProperty(exports, "V2CreateRoleRequest", { enumerable: true, get: function () { return V2CreateRoleRequest_1.V2CreateRoleRequest; } });
var V2UpdateRoleRequest_1 = require("./V2UpdateRoleRequest");
Object.defineProperty(exports, "V2UpdateRoleRequest", { enumerable: true, get: function () { return V2UpdateRoleRequest_1.V2UpdateRoleRequest; } });
