/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../..";
import * as PolytomicApi from "../../../../../api";
import * as core from "../../../../../core";
export declare const V2UpdateRoleRequest: core.serialization.Schema<serializers.V2UpdateRoleRequest.Raw, PolytomicApi.V2UpdateRoleRequest>;
export declare namespace V2UpdateRoleRequest {
    interface Raw {
        name: string;
        organization_id?: string | null;
    }
}
