/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as environments from "../../../../environments";
import * as core from "../../../../core";
import * as PolytomicApi from "../../..";
export declare namespace ModelSync {
    interface Options {
        environment?: core.Supplier<environments.PolytomicApiEnvironment | string>;
        token: core.Supplier<core.BearerToken>;
    }
    interface RequestOptions {
        timeoutInSeconds?: number;
    }
}
export declare class ModelSync {
    protected readonly _options: ModelSync.Options;
    constructor(_options: ModelSync.Options);
    /**
     * @throws {@link PolytomicApi.UnauthorizedError}
     */
    apiV2ListSyncs(requestOptions?: ModelSync.RequestOptions): Promise<PolytomicApi.V2ListSyncResponseEnvelope>;
    /**
     * @throws {@link PolytomicApi.UnauthorizedError}
     */
    apiV2CreateSync(request: PolytomicApi.V2CreateSyncRequest, requestOptions?: ModelSync.RequestOptions): Promise<PolytomicApi.V2SyncResponseEnvelope>;
    /**
     * @throws {@link PolytomicApi.UnauthorizedError}
     */
    apiV2GetSync(id: string, requestOptions?: ModelSync.RequestOptions): Promise<PolytomicApi.V2SyncResponseEnvelope>;
    /**
     * @throws {@link PolytomicApi.UnauthorizedError}
     */
    apiV2RemoveSync(id: string, requestOptions?: ModelSync.RequestOptions): Promise<void>;
    /**
     * @throws {@link PolytomicApi.UnauthorizedError}
     */
    apiV2UpdateSync(id: string, request: PolytomicApi.V2UpdateSyncRequest, requestOptions?: ModelSync.RequestOptions): Promise<PolytomicApi.V2SyncResponseEnvelope>;
    /**
     * @throws {@link PolytomicApi.UnauthorizedError}
     */
    apiV2ActivateSync(id: string, request: PolytomicApi.V2ActivateSyncInput, requestOptions?: ModelSync.RequestOptions): Promise<PolytomicApi.V2ActivateSyncEnvelope>;
    /**
     * @throws {@link PolytomicApi.UnauthorizedError}
     */
    apiV2StartSync(id: string, request?: PolytomicApi.V2StartSyncRequest, requestOptions?: ModelSync.RequestOptions): Promise<PolytomicApi.V2StartSyncResponseEnvelope>;
    /**
     * @throws {@link PolytomicApi.UnauthorizedError}
     */
    apiV2GetSyncStatus(id: string, requestOptions?: ModelSync.RequestOptions): Promise<PolytomicApi.V2SyncStatusEnvelope>;
    /**
     * @throws {@link PolytomicApi.UnauthorizedError}
     */
    apiV2ListExecutions(syncId: string, requestOptions?: ModelSync.RequestOptions): Promise<PolytomicApi.V2ListExecutionResponseEnvelope>;
    /**
     * @throws {@link PolytomicApi.UnauthorizedError}
     */
    apiV2GetExecution(syncId: string, id: string, requestOptions?: ModelSync.RequestOptions): Promise<PolytomicApi.V2GetExecutionResponseEnvelope>;
    protected _getAuthorizationHeader(): Promise<string>;
}
