// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         limit: 50,
 *         page_token: "page_token"
 *     }
 */
export interface HarborsListUsersRequest {
    /** Maximum number of assigned users to return. Defaults to 50 and cannot exceed 50. */
    limit?: number;
    /** Opaque pagination cursor returned by the previous request. */
    page_token?: string;
}
