// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         limit: 1,
 *         page_token: "page_token"
 *     }
 */
export interface HarborsListSavedQueryDraftsRequest {
    /** Maximum number of saved-query drafts to return. */
    limit?: number;
    /** Opaque pagination cursor returned by the previous request. */
    page_token?: string;
}
