// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface HarborsCloseSessionRequest {
    "X-Polytomic-MCP-Key-ID"?: string;
    "X-Polytomic-MCP-Timestamp"?: number;
    "X-Polytomic-MCP-Nonce"?: string;
    "X-Polytomic-MCP-Signature"?: string;
    "X-Polytomic-Activity-Request-ID"?: string;
    "X-Polytomic-Harbor-Session"?: string;
}
