// This file was auto-generated by Fern from our API Definition.

/** Order in which events were recorded. Defaults to asc. */
export const ActivityGetSessionRequestOrder = {
    Asc: "asc",
    Desc: "desc",
} as const;
export type ActivityGetSessionRequestOrder =
    (typeof ActivityGetSessionRequestOrder)[keyof typeof ActivityGetSessionRequestOrder];
