/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../environments";
import * as core from "../../../../core";
import * as Polytomic from "../../../index";
import { toJson } from "../../../../core/json";
import urlJoin from "url-join";
import * as errors from "../../../../errors/index";

export declare namespace Connections {
    export interface Options {
        environment?: core.Supplier<environments.PolytomicEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        token: core.Supplier<core.BearerToken>;
        /** Override the X-Polytomic-Version header */
        version?: core.Supplier<unknown>;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Override the X-Polytomic-Version header */
        version?: unknown;
        /** Additional headers to include in the request. */
        headers?: Record<string, string>;
    }
}

export class Connections {
    constructor(protected readonly _options: Connections.Options) {}

    /**
     * @param {Connections.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Polytomic.UnauthorizedError}
     * @throws {@link Polytomic.InternalServerError}
     *
     * @example
     *     await client.connections.getTypes()
     */
    public getTypes(
        requestOptions?: Connections.RequestOptions,
    ): core.HttpResponsePromise<Polytomic.ConnectionTypeResponseEnvelope> {
        return core.HttpResponsePromise.fromPromise(this.__getTypes(requestOptions));
    }

    private async __getTypes(
        requestOptions?: Connections.RequestOptions,
    ): Promise<core.WithRawResponse<Polytomic.ConnectionTypeResponseEnvelope>> {
        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PolytomicEnvironment.Default,
                "api/connection_types",
            ),
            method: "GET",
            headers: {
                Authorization: await this._getAuthorizationHeader(),
                "X-Polytomic-Version":
                    typeof (await core.Supplier.get(this._options.version)) === "string"
                        ? await core.Supplier.get(this._options.version)
                        : toJson(await core.Supplier.get(this._options.version)),
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "",
                "X-Fern-SDK-Version": "1.16.2",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            requestType: "json",
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: _response.body as Polytomic.ConnectionTypeResponseEnvelope,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Polytomic.UnauthorizedError(
                        _response.error.body as Polytomic.RestErrResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Polytomic.InternalServerError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.PolytomicError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.PolytomicError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.PolytomicTimeoutError("Timeout exceeded when calling GET /api/connection_types.");
            case "unknown":
                throw new errors.PolytomicError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * @param {string} id
     * @param {Polytomic.ConnectionsGetConnectionTypeSchemaRequest} request
     * @param {Connections.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Polytomic.UnauthorizedError}
     * @throws {@link Polytomic.NotFoundError}
     * @throws {@link Polytomic.InternalServerError}
     *
     * @example
     *     await client.connections.getConnectionTypeSchema("postgresql")
     */
    public getConnectionTypeSchema(
        id: string,
        request: Polytomic.ConnectionsGetConnectionTypeSchemaRequest = {},
        requestOptions?: Connections.RequestOptions,
    ): core.HttpResponsePromise<Polytomic.JsonschemaSchema> {
        return core.HttpResponsePromise.fromPromise(this.__getConnectionTypeSchema(id, request, requestOptions));
    }

    private async __getConnectionTypeSchema(
        id: string,
        request: Polytomic.ConnectionsGetConnectionTypeSchemaRequest = {},
        requestOptions?: Connections.RequestOptions,
    ): Promise<core.WithRawResponse<Polytomic.JsonschemaSchema>> {
        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PolytomicEnvironment.Default,
                `api/connection_types/${encodeURIComponent(id)}`,
            ),
            method: "GET",
            headers: {
                Authorization: await this._getAuthorizationHeader(),
                "X-Polytomic-Version":
                    typeof (await core.Supplier.get(this._options.version)) === "string"
                        ? await core.Supplier.get(this._options.version)
                        : toJson(await core.Supplier.get(this._options.version)),
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "",
                "X-Fern-SDK-Version": "1.16.2",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            requestType: "json",
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as Polytomic.JsonschemaSchema, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Polytomic.UnauthorizedError(
                        _response.error.body as Polytomic.RestErrResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Polytomic.NotFoundError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Polytomic.InternalServerError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.PolytomicError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.PolytomicError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.PolytomicTimeoutError("Timeout exceeded when calling GET /api/connection_types/{id}.");
            case "unknown":
                throw new errors.PolytomicError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * @param {string} type_
     * @param {Polytomic.GetConnectionTypeParameterValuesRequestSchema} request
     * @param {Connections.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Polytomic.BadRequestError}
     * @throws {@link Polytomic.UnauthorizedError}
     * @throws {@link Polytomic.NotFoundError}
     * @throws {@link Polytomic.InternalServerError}
     *
     * @example
     *     await client.connections.getTypeParameterValues("type", {
     *         field: "field"
     *     })
     */
    public getTypeParameterValues(
        type_: string,
        request: Polytomic.GetConnectionTypeParameterValuesRequestSchema,
        requestOptions?: Connections.RequestOptions,
    ): core.HttpResponsePromise<Polytomic.ConnectionParameterValuesResponseEnvelope> {
        return core.HttpResponsePromise.fromPromise(this.__getTypeParameterValues(type_, request, requestOptions));
    }

    private async __getTypeParameterValues(
        type_: string,
        request: Polytomic.GetConnectionTypeParameterValuesRequestSchema,
        requestOptions?: Connections.RequestOptions,
    ): Promise<core.WithRawResponse<Polytomic.ConnectionParameterValuesResponseEnvelope>> {
        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PolytomicEnvironment.Default,
                `api/connection_types/${encodeURIComponent(type_)}/parameter_values`,
            ),
            method: "POST",
            headers: {
                Authorization: await this._getAuthorizationHeader(),
                "X-Polytomic-Version":
                    typeof (await core.Supplier.get(this._options.version)) === "string"
                        ? await core.Supplier.get(this._options.version)
                        : toJson(await core.Supplier.get(this._options.version)),
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "",
                "X-Fern-SDK-Version": "1.16.2",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            requestType: "json",
            body: request,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: _response.body as Polytomic.ConnectionParameterValuesResponseEnvelope,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Polytomic.BadRequestError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                case 401:
                    throw new Polytomic.UnauthorizedError(
                        _response.error.body as Polytomic.RestErrResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Polytomic.NotFoundError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Polytomic.InternalServerError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.PolytomicError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.PolytomicError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.PolytomicTimeoutError(
                    "Timeout exceeded when calling POST /api/connection_types/{type}/parameter_values.",
                );
            case "unknown":
                throw new errors.PolytomicError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * @param {Connections.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Polytomic.UnauthorizedError}
     * @throws {@link Polytomic.InternalServerError}
     *
     * @example
     *     await client.connections.list()
     */
    public list(
        requestOptions?: Connections.RequestOptions,
    ): core.HttpResponsePromise<Polytomic.ConnectionListResponseEnvelope> {
        return core.HttpResponsePromise.fromPromise(this.__list(requestOptions));
    }

    private async __list(
        requestOptions?: Connections.RequestOptions,
    ): Promise<core.WithRawResponse<Polytomic.ConnectionListResponseEnvelope>> {
        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PolytomicEnvironment.Default,
                "api/connections",
            ),
            method: "GET",
            headers: {
                Authorization: await this._getAuthorizationHeader(),
                "X-Polytomic-Version":
                    typeof (await core.Supplier.get(this._options.version)) === "string"
                        ? await core.Supplier.get(this._options.version)
                        : toJson(await core.Supplier.get(this._options.version)),
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "",
                "X-Fern-SDK-Version": "1.16.2",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            requestType: "json",
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: _response.body as Polytomic.ConnectionListResponseEnvelope,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Polytomic.UnauthorizedError(
                        _response.error.body as Polytomic.RestErrResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Polytomic.InternalServerError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.PolytomicError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.PolytomicError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.PolytomicTimeoutError("Timeout exceeded when calling GET /api/connections.");
            case "unknown":
                throw new errors.PolytomicError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * @param {Polytomic.CreateConnectionRequestSchema} request
     * @param {Connections.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Polytomic.BadRequestError}
     * @throws {@link Polytomic.UnauthorizedError}
     * @throws {@link Polytomic.ForbiddenError}
     * @throws {@link Polytomic.UnprocessableEntityError}
     * @throws {@link Polytomic.InternalServerError}
     *
     * @example
     *     await client.connections.create({
     *         configuration: {
     *             "database": "example",
     *             "hostname": "postgres.example.com",
     *             "password": "********",
     *             "port": 5432,
     *             "username": "user"
     *         },
     *         name: "My Postgres Connection",
     *         type: "postgresql"
     *     })
     */
    public create(
        request: Polytomic.CreateConnectionRequestSchema,
        requestOptions?: Connections.RequestOptions,
    ): core.HttpResponsePromise<Polytomic.CreateConnectionResponseEnvelope> {
        return core.HttpResponsePromise.fromPromise(this.__create(request, requestOptions));
    }

    private async __create(
        request: Polytomic.CreateConnectionRequestSchema,
        requestOptions?: Connections.RequestOptions,
    ): Promise<core.WithRawResponse<Polytomic.CreateConnectionResponseEnvelope>> {
        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PolytomicEnvironment.Default,
                "api/connections",
            ),
            method: "POST",
            headers: {
                Authorization: await this._getAuthorizationHeader(),
                "X-Polytomic-Version":
                    typeof (await core.Supplier.get(this._options.version)) === "string"
                        ? await core.Supplier.get(this._options.version)
                        : toJson(await core.Supplier.get(this._options.version)),
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "",
                "X-Fern-SDK-Version": "1.16.2",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            requestType: "json",
            body: request,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: _response.body as Polytomic.CreateConnectionResponseEnvelope,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Polytomic.BadRequestError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                case 401:
                    throw new Polytomic.UnauthorizedError(
                        _response.error.body as Polytomic.RestErrResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Polytomic.ForbiddenError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                case 422:
                    throw new Polytomic.UnprocessableEntityError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Polytomic.InternalServerError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.PolytomicError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.PolytomicError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.PolytomicTimeoutError("Timeout exceeded when calling POST /api/connections.");
            case "unknown":
                throw new errors.PolytomicError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Creates a new request for [Polytomic Connect](https://www.polytomic.com/connect).
     *
     * This endpoint configures a Polytomic Connect request and returns the URL to
     * redirect users to. This allows embedding Polytomic connection authorization in
     * other applications.
     *
     * See also:
     *
     * - [Embedding authentication](https://apidocs.polytomic.com/2024-02-08/guides/embedding-authentication), a guide to using Polytomic Connect.
     *
     * @param {Polytomic.ConnectCardRequest} request
     * @param {Connections.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Polytomic.UnauthorizedError}
     * @throws {@link Polytomic.ForbiddenError}
     * @throws {@link Polytomic.UnprocessableEntityError}
     * @throws {@link Polytomic.InternalServerError}
     *
     * @example
     *     await client.connections.connect({
     *         name: "Salesforce Connection",
     *         redirect_url: "redirect_url"
     *     })
     */
    public connect(
        request: Polytomic.ConnectCardRequest,
        requestOptions?: Connections.RequestOptions,
    ): core.HttpResponsePromise<Polytomic.ConnectCardResponseEnvelope> {
        return core.HttpResponsePromise.fromPromise(this.__connect(request, requestOptions));
    }

    private async __connect(
        request: Polytomic.ConnectCardRequest,
        requestOptions?: Connections.RequestOptions,
    ): Promise<core.WithRawResponse<Polytomic.ConnectCardResponseEnvelope>> {
        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PolytomicEnvironment.Default,
                "api/connections/connect/",
            ),
            method: "POST",
            headers: {
                Authorization: await this._getAuthorizationHeader(),
                "X-Polytomic-Version":
                    typeof (await core.Supplier.get(this._options.version)) === "string"
                        ? await core.Supplier.get(this._options.version)
                        : toJson(await core.Supplier.get(this._options.version)),
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "",
                "X-Fern-SDK-Version": "1.16.2",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            requestType: "json",
            body: request,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: _response.body as Polytomic.ConnectCardResponseEnvelope,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Polytomic.UnauthorizedError(
                        _response.error.body as Polytomic.RestErrResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Polytomic.ForbiddenError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                case 422:
                    throw new Polytomic.UnprocessableEntityError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Polytomic.InternalServerError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.PolytomicError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.PolytomicError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.PolytomicTimeoutError("Timeout exceeded when calling POST /api/connections/connect/.");
            case "unknown":
                throw new errors.PolytomicError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Tests a connection configuration.
     *
     * @param {Polytomic.TestConnectionRequest} request
     * @param {Connections.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Polytomic.BadRequestError}
     * @throws {@link Polytomic.UnauthorizedError}
     * @throws {@link Polytomic.NotFoundError}
     * @throws {@link Polytomic.InternalServerError}
     *
     * @example
     *     await client.connections.testConnection({
     *         configuration: {
     *             "database": "example",
     *             "hostname": "postgres.example.com",
     *             "password": "password",
     *             "port": 5432,
     *             "username": "user"
     *         },
     *         type: "postgresql"
     *     })
     */
    public testConnection(
        request: Polytomic.TestConnectionRequest,
        requestOptions?: Connections.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__testConnection(request, requestOptions));
    }

    private async __testConnection(
        request: Polytomic.TestConnectionRequest,
        requestOptions?: Connections.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PolytomicEnvironment.Default,
                "api/connections/test",
            ),
            method: "POST",
            headers: {
                Authorization: await this._getAuthorizationHeader(),
                "X-Polytomic-Version":
                    typeof (await core.Supplier.get(this._options.version)) === "string"
                        ? await core.Supplier.get(this._options.version)
                        : toJson(await core.Supplier.get(this._options.version)),
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "",
                "X-Fern-SDK-Version": "1.16.2",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            requestType: "json",
            body: request,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Polytomic.BadRequestError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                case 401:
                    throw new Polytomic.UnauthorizedError(
                        _response.error.body as Polytomic.RestErrResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Polytomic.NotFoundError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Polytomic.InternalServerError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.PolytomicError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.PolytomicError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.PolytomicTimeoutError("Timeout exceeded when calling POST /api/connections/test.");
            case "unknown":
                throw new errors.PolytomicError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * @param {string} id
     * @param {Polytomic.ConnectionsGetRequest} request
     * @param {Connections.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Polytomic.UnauthorizedError}
     * @throws {@link Polytomic.NotFoundError}
     * @throws {@link Polytomic.InternalServerError}
     *
     * @example
     *     await client.connections.get("248df4b7-aa70-47b8-a036-33ac447e668d")
     */
    public get(
        id: string,
        request: Polytomic.ConnectionsGetRequest = {},
        requestOptions?: Connections.RequestOptions,
    ): core.HttpResponsePromise<Polytomic.ConnectionResponseEnvelope> {
        return core.HttpResponsePromise.fromPromise(this.__get(id, request, requestOptions));
    }

    private async __get(
        id: string,
        request: Polytomic.ConnectionsGetRequest = {},
        requestOptions?: Connections.RequestOptions,
    ): Promise<core.WithRawResponse<Polytomic.ConnectionResponseEnvelope>> {
        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PolytomicEnvironment.Default,
                `api/connections/${encodeURIComponent(id)}`,
            ),
            method: "GET",
            headers: {
                Authorization: await this._getAuthorizationHeader(),
                "X-Polytomic-Version":
                    typeof (await core.Supplier.get(this._options.version)) === "string"
                        ? await core.Supplier.get(this._options.version)
                        : toJson(await core.Supplier.get(this._options.version)),
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "",
                "X-Fern-SDK-Version": "1.16.2",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            requestType: "json",
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as Polytomic.ConnectionResponseEnvelope, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Polytomic.UnauthorizedError(
                        _response.error.body as Polytomic.RestErrResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Polytomic.NotFoundError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Polytomic.InternalServerError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.PolytomicError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.PolytomicError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.PolytomicTimeoutError("Timeout exceeded when calling GET /api/connections/{id}.");
            case "unknown":
                throw new errors.PolytomicError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * @param {string} id
     * @param {Polytomic.UpdateConnectionRequestSchema} request
     * @param {Connections.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Polytomic.BadRequestError}
     * @throws {@link Polytomic.UnauthorizedError}
     * @throws {@link Polytomic.ForbiddenError}
     * @throws {@link Polytomic.NotFoundError}
     * @throws {@link Polytomic.UnprocessableEntityError}
     * @throws {@link Polytomic.InternalServerError}
     *
     * @example
     *     await client.connections.update("248df4b7-aa70-47b8-a036-33ac447e668d", {
     *         configuration: {
     *             "database": "example",
     *             "hostname": "postgres.example.com",
     *             "password": "********",
     *             "port": 5432,
     *             "username": "user"
     *         },
     *         name: "My Postgres Connection"
     *     })
     */
    public update(
        id: string,
        request: Polytomic.UpdateConnectionRequestSchema,
        requestOptions?: Connections.RequestOptions,
    ): core.HttpResponsePromise<Polytomic.CreateConnectionResponseEnvelope> {
        return core.HttpResponsePromise.fromPromise(this.__update(id, request, requestOptions));
    }

    private async __update(
        id: string,
        request: Polytomic.UpdateConnectionRequestSchema,
        requestOptions?: Connections.RequestOptions,
    ): Promise<core.WithRawResponse<Polytomic.CreateConnectionResponseEnvelope>> {
        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PolytomicEnvironment.Default,
                `api/connections/${encodeURIComponent(id)}`,
            ),
            method: "PUT",
            headers: {
                Authorization: await this._getAuthorizationHeader(),
                "X-Polytomic-Version":
                    typeof (await core.Supplier.get(this._options.version)) === "string"
                        ? await core.Supplier.get(this._options.version)
                        : toJson(await core.Supplier.get(this._options.version)),
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "",
                "X-Fern-SDK-Version": "1.16.2",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            requestType: "json",
            body: request,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: _response.body as Polytomic.CreateConnectionResponseEnvelope,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Polytomic.BadRequestError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                case 401:
                    throw new Polytomic.UnauthorizedError(
                        _response.error.body as Polytomic.RestErrResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Polytomic.ForbiddenError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Polytomic.NotFoundError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                case 422:
                    throw new Polytomic.UnprocessableEntityError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Polytomic.InternalServerError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.PolytomicError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.PolytomicError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.PolytomicTimeoutError("Timeout exceeded when calling PUT /api/connections/{id}.");
            case "unknown":
                throw new errors.PolytomicError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * @param {string} id
     * @param {Polytomic.ConnectionsRemoveRequest} request
     * @param {Connections.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Polytomic.UnauthorizedError}
     * @throws {@link Polytomic.ForbiddenError}
     * @throws {@link Polytomic.NotFoundError}
     * @throws {@link Polytomic.UnprocessableEntityError}
     * @throws {@link Polytomic.InternalServerError}
     *
     * @example
     *     await client.connections.remove("248df4b7-aa70-47b8-a036-33ac447e668d", {
     *         force: true
     *     })
     */
    public remove(
        id: string,
        request: Polytomic.ConnectionsRemoveRequest = {},
        requestOptions?: Connections.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__remove(id, request, requestOptions));
    }

    private async __remove(
        id: string,
        request: Polytomic.ConnectionsRemoveRequest = {},
        requestOptions?: Connections.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const { force } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (force != null) {
            _queryParams["force"] = force.toString();
        }

        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PolytomicEnvironment.Default,
                `api/connections/${encodeURIComponent(id)}`,
            ),
            method: "DELETE",
            headers: {
                Authorization: await this._getAuthorizationHeader(),
                "X-Polytomic-Version":
                    typeof (await core.Supplier.get(this._options.version)) === "string"
                        ? await core.Supplier.get(this._options.version)
                        : toJson(await core.Supplier.get(this._options.version)),
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "",
                "X-Fern-SDK-Version": "1.16.2",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            queryParameters: _queryParams,
            requestType: "json",
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Polytomic.UnauthorizedError(
                        _response.error.body as Polytomic.RestErrResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Polytomic.ForbiddenError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Polytomic.NotFoundError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                case 422:
                    throw new Polytomic.UnprocessableEntityError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Polytomic.InternalServerError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.PolytomicError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.PolytomicError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.PolytomicTimeoutError("Timeout exceeded when calling DELETE /api/connections/{id}.");
            case "unknown":
                throw new errors.PolytomicError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * @param {string} id
     * @param {Polytomic.ConnectionsGetParameterValuesRequest} request
     * @param {Connections.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Polytomic.UnauthorizedError}
     * @throws {@link Polytomic.NotFoundError}
     * @throws {@link Polytomic.InternalServerError}
     *
     * @example
     *     await client.connections.getParameterValues("248df4b7-aa70-47b8-a036-33ac447e668d")
     */
    public getParameterValues(
        id: string,
        request: Polytomic.ConnectionsGetParameterValuesRequest = {},
        requestOptions?: Connections.RequestOptions,
    ): core.HttpResponsePromise<Polytomic.ConnectionParameterValuesResponseEnvelope> {
        return core.HttpResponsePromise.fromPromise(this.__getParameterValues(id, request, requestOptions));
    }

    private async __getParameterValues(
        id: string,
        request: Polytomic.ConnectionsGetParameterValuesRequest = {},
        requestOptions?: Connections.RequestOptions,
    ): Promise<core.WithRawResponse<Polytomic.ConnectionParameterValuesResponseEnvelope>> {
        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PolytomicEnvironment.Default,
                `api/connections/${encodeURIComponent(id)}/parameter_values`,
            ),
            method: "GET",
            headers: {
                Authorization: await this._getAuthorizationHeader(),
                "X-Polytomic-Version":
                    typeof (await core.Supplier.get(this._options.version)) === "string"
                        ? await core.Supplier.get(this._options.version)
                        : toJson(await core.Supplier.get(this._options.version)),
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "",
                "X-Fern-SDK-Version": "1.16.2",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            requestType: "json",
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: _response.body as Polytomic.ConnectionParameterValuesResponseEnvelope,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Polytomic.UnauthorizedError(
                        _response.error.body as Polytomic.RestErrResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Polytomic.NotFoundError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Polytomic.InternalServerError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.PolytomicError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.PolytomicError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.PolytomicTimeoutError(
                    "Timeout exceeded when calling GET /api/connections/{id}/parameter_values.",
                );
            case "unknown":
                throw new errors.PolytomicError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * > 🚧 Requires partner key
     * >
     * > Shared connections can only be created by using [partner keys](https://apidocs.polytomic.com/guides/obtaining-api-keys#partner-keys).
     *
     * @param {string} parentConnectionId
     * @param {Polytomic.ApiRequest} request
     * @param {Connections.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Polytomic.UnauthorizedError}
     * @throws {@link Polytomic.ForbiddenError}
     * @throws {@link Polytomic.NotFoundError}
     * @throws {@link Polytomic.UnprocessableEntityError}
     * @throws {@link Polytomic.InternalServerError}
     *
     * @example
     *     await client.connections.createSharedConnection("248df4b7-aa70-47b8-a036-33ac447e668d", {
     *         child_organization_id: "248df4b7-aa70-47b8-a036-33ac447e668d"
     *     })
     */
    public createSharedConnection(
        parentConnectionId: string,
        request: Polytomic.ApiRequest,
        requestOptions?: Connections.RequestOptions,
    ): core.HttpResponsePromise<Polytomic.V2CreateSharedConnectionResponseEnvelope> {
        return core.HttpResponsePromise.fromPromise(
            this.__createSharedConnection(parentConnectionId, request, requestOptions),
        );
    }

    private async __createSharedConnection(
        parentConnectionId: string,
        request: Polytomic.ApiRequest,
        requestOptions?: Connections.RequestOptions,
    ): Promise<core.WithRawResponse<Polytomic.V2CreateSharedConnectionResponseEnvelope>> {
        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PolytomicEnvironment.Default,
                `api/connections/${encodeURIComponent(parentConnectionId)}/share`,
            ),
            method: "POST",
            headers: {
                Authorization: await this._getAuthorizationHeader(),
                "X-Polytomic-Version":
                    typeof (await core.Supplier.get(this._options.version)) === "string"
                        ? await core.Supplier.get(this._options.version)
                        : toJson(await core.Supplier.get(this._options.version)),
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "",
                "X-Fern-SDK-Version": "1.16.2",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            requestType: "json",
            body: request,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: _response.body as Polytomic.V2CreateSharedConnectionResponseEnvelope,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Polytomic.UnauthorizedError(
                        _response.error.body as Polytomic.RestErrResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Polytomic.ForbiddenError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Polytomic.NotFoundError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                case 422:
                    throw new Polytomic.UnprocessableEntityError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Polytomic.InternalServerError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.PolytomicError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.PolytomicError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.PolytomicTimeoutError(
                    "Timeout exceeded when calling POST /api/connections/{parent_connection_id}/share.",
                );
            case "unknown":
                throw new errors.PolytomicError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * @param {string} parentConnectionId
     * @param {Polytomic.ConnectionsListSharedConnectionsRequest} request
     * @param {Connections.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Polytomic.UnauthorizedError}
     * @throws {@link Polytomic.ForbiddenError}
     * @throws {@link Polytomic.NotFoundError}
     * @throws {@link Polytomic.UnprocessableEntityError}
     * @throws {@link Polytomic.InternalServerError}
     *
     * @example
     *     await client.connections.listSharedConnections("248df4b7-aa70-47b8-a036-33ac447e668d")
     */
    public listSharedConnections(
        parentConnectionId: string,
        request: Polytomic.ConnectionsListSharedConnectionsRequest = {},
        requestOptions?: Connections.RequestOptions,
    ): core.HttpResponsePromise<Polytomic.ConnectionListResponseEnvelope> {
        return core.HttpResponsePromise.fromPromise(
            this.__listSharedConnections(parentConnectionId, request, requestOptions),
        );
    }

    private async __listSharedConnections(
        parentConnectionId: string,
        request: Polytomic.ConnectionsListSharedConnectionsRequest = {},
        requestOptions?: Connections.RequestOptions,
    ): Promise<core.WithRawResponse<Polytomic.ConnectionListResponseEnvelope>> {
        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PolytomicEnvironment.Default,
                `api/connections/${encodeURIComponent(parentConnectionId)}/shared`,
            ),
            method: "GET",
            headers: {
                Authorization: await this._getAuthorizationHeader(),
                "X-Polytomic-Version":
                    typeof (await core.Supplier.get(this._options.version)) === "string"
                        ? await core.Supplier.get(this._options.version)
                        : toJson(await core.Supplier.get(this._options.version)),
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "",
                "X-Fern-SDK-Version": "1.16.2",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            requestType: "json",
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: _response.body as Polytomic.ConnectionListResponseEnvelope,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Polytomic.UnauthorizedError(
                        _response.error.body as Polytomic.RestErrResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Polytomic.ForbiddenError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Polytomic.NotFoundError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                case 422:
                    throw new Polytomic.UnprocessableEntityError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Polytomic.InternalServerError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.PolytomicError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.PolytomicError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.PolytomicTimeoutError(
                    "Timeout exceeded when calling GET /api/connections/{parent_connection_id}/shared.",
                );
            case "unknown":
                throw new errors.PolytomicError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    protected async _getAuthorizationHeader(): Promise<string> {
        return `Bearer ${await core.Supplier.get(this._options.token)}`;
    }
}
