"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.V3UpdateBulkSchema = exports.V3BulkSyncSchemasRequest = exports.V3StartBulkSyncRequest = exports.V2UpdateBulkSyncRequest = exports.V2CreateBulkSyncRequest = void 0;
var V2CreateBulkSyncRequest_1 = require("./V2CreateBulkSyncRequest");
Object.defineProperty(exports, "V2CreateBulkSyncRequest", { enumerable: true, get: function () { return V2CreateBulkSyncRequest_1.V2CreateBulkSyncRequest; } });
var V2UpdateBulkSyncRequest_1 = require("./V2UpdateBulkSyncRequest");
Object.defineProperty(exports, "V2UpdateBulkSyncRequest", { enumerable: true, get: function () { return V2UpdateBulkSyncRequest_1.V2UpdateBulkSyncRequest; } });
var V3StartBulkSyncRequest_1 = require("./V3StartBulkSyncRequest");
Object.defineProperty(exports, "V3StartBulkSyncRequest", { enumerable: true, get: function () { return V3StartBulkSyncRequest_1.V3StartBulkSyncRequest; } });
var V3BulkSyncSchemasRequest_1 = require("./V3BulkSyncSchemasRequest");
Object.defineProperty(exports, "V3BulkSyncSchemasRequest", { enumerable: true, get: function () { return V3BulkSyncSchemasRequest_1.V3BulkSyncSchemasRequest; } });
var V3UpdateBulkSchema_1 = require("./V3UpdateBulkSchema");
Object.defineProperty(exports, "V3UpdateBulkSchema", { enumerable: true, get: function () { return V3UpdateBulkSchema_1.V3UpdateBulkSchema; } });
