/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface BackendConnectionCapabilities {
    destination: boolean;
    enrichment: boolean;
    orchestration: boolean;
    source: boolean;
}
