// This file was auto-generated by Fern from our API Definition.

import type * as Polytomic from "../index";

export interface BulkSyncResponse {
    active?: boolean | undefined;
    automatically_add_new_fields?: Polytomic.BulkDiscover | undefined;
    automatically_add_new_objects?: Polytomic.BulkDiscover | undefined;
    /** Per-sync concurrency limit override. */
    concurrency_limit?: number | undefined;
    created_at?: string | undefined;
    created_by?: Polytomic.CommonOutputActor | undefined;
    data_cutoff_timestamp?: string | undefined;
    /** Destination-specific bulk sync configuration. e.g. output schema name, s3 file format, etc. */
    destination_configuration?: Record<string, unknown> | undefined;
    destination_connection_id?: string | undefined;
    disable_record_timestamps?: boolean | undefined;
    /** DEPRECATED: Use automatically_add_new_objects/automatically_add_new_fields instead */
    discover?: boolean | undefined;
    id?: string | undefined;
    mode?: Polytomic.BulkSyncMode | undefined;
    /** Name of the bulk sync */
    name?: string | undefined;
    normalize_names?: Polytomic.BulkNormalizeNames | undefined;
    organization_id?: string | undefined;
    /** List of permissions policies applied to the bulk sync. */
    policies?: string[] | undefined;
    /** Per-sync resync concurrency limit override. */
    resync_concurrency_limit?: number | undefined;
    schedule?: Polytomic.BulkSchedule | undefined;
    /** Source-specific bulk sync configuration. e.g. replication slot name, sync lookback, etc. */
    source_configuration?: Record<string, unknown> | undefined;
    source_connection_id?: string | undefined;
    updated_at?: string | undefined;
    updated_by?: Polytomic.CommonOutputActor | undefined;
}
