// This file was auto-generated by Fern from our API Definition.

import type * as Polytomic from "../index";

export interface BulkSyncAdditionalScheduleResponse {
    /** Timestamp the schedule was created. */
    created_at?: string | undefined;
    created_by?: Polytomic.OutputActor | undefined;
    /** Day of the month (1-31) for monthly schedules. */
    day_of_month?: string | undefined;
    /** Day of the week for weekly schedules. */
    day_of_week?: string | undefined;
    frequency: Polytomic.ScheduleFrequency;
    /** Hour of the day (0-23, in UTC) the schedule fires. */
    hour?: string | undefined;
    /** Unique identifier of the schedule. */
    id?: string | undefined;
    /** Minute of the hour (0-59) the schedule fires. */
    minute?: string | undefined;
    /** Month of the year (1-12) for yearly schedules. */
    month?: string | undefined;
    resync_mode?: Polytomic.BulkScheduleSyncMode | undefined;
    /** Schema IDs this schedule applies to. Empty means all schemas. */
    schemas?: string[] | undefined;
    selective_mode?: Polytomic.BulkSelectiveMode | undefined;
    /** Timestamp the schedule was last updated. */
    updated_at?: string | undefined;
    updated_by?: Polytomic.OutputActor | undefined;
}
