/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Polytomic from "../index";

export interface BulkSyncSchemaExecution {
    completed_at?: string;
    created_at?: string;
    error_count?: number;
    output_name?: string;
    record_count?: number;
    schema?: string;
    started_at?: string;
    status?: Polytomic.BulkSchemaExecutionStatus;
    status_message?: string;
    updated_at?: string;
    warning_count?: number;
}
