// This file was auto-generated by Fern from our API Definition.

export interface BulkSyncErrorHandling {
    /** How far behind ingestion may fall before a terminal execution is failed, in the unit this sync's source reports: seconds for a source carrying event timestamps, outstanding items for a queue-backed source such as S3. Null means this sync has no threshold of its own: a source reporting seconds then follows the deployment-wide default, while a queue-backed source is left unchecked. */
    ingestion_failure_threshold?: number | undefined;
    /** Email addresses notified when this sync fails. */
    subscribers?: string[] | undefined;
}
