// This file was auto-generated by Fern from our API Definition.

import type * as Polytomic from "../index";

export interface BulkSyncExecution {
    completed_at?: string | undefined;
    created_at?: string | undefined;
    error_count?: number | undefined;
    fetch_mode?: Polytomic.BulkFetchMode | undefined;
    id?: string | undefined;
    is_partial?: boolean | undefined;
    is_resync?: boolean | undefined;
    is_test?: boolean | undefined;
    record_count?: number | undefined;
    schemas?: Polytomic.BulkSyncSchemaExecution[] | undefined;
    started_at?: string | undefined;
    status?: Polytomic.BulkExecutionStatus | undefined;
    status_message?: string | undefined;
    type?: string | undefined;
    updated_at?: string | undefined;
    warning_count?: number | undefined;
}
