// This file was auto-generated by Fern from our API Definition.

export interface BulkSyncCompletedEvent {
    destination_connection_id?: string | undefined;
    execution_id?: string | undefined;
    organization_id?: string | undefined;
    source_connection_id?: string | undefined;
    sync_id?: string | undefined;
    sync_name?: string | undefined;
    trigger_source?: string | undefined;
}
