// This file was auto-generated by Fern from our API Definition.

import type * as Polytomic from "../index";

export interface CreateHarborResponse {
    api_key?: Polytomic.HarborApiKeyCreatedResponse | undefined;
    harbor?: Polytomic.HarborResponse | undefined;
}
