// This file was auto-generated by Fern from our API Definition.

import type * as Polytomic from "../index";

export interface CreateConnectionResponseSchema {
    /** Code to enter in order to complete connection authentication. */
    auth_code?: string | undefined;
    /** URL to visit to complete connection authentication. */
    auth_url?: string | undefined;
    configuration?: Record<string, unknown> | undefined;
    /** Interval for connection health checking. */
    healthcheck_interval?: string | undefined;
    id?: string | undefined;
    name?: string | undefined;
    organization_id?: string | undefined;
    policies?: string[] | undefined;
    saved?: boolean | undefined;
    status?: string | undefined;
    status_error?: string | undefined;
    type?: Polytomic.ConnectionTypeSchema | undefined;
}
