// This file was auto-generated by Fern from our API Definition.

import type * as Polytomic from "../index";

export interface EntityResponse {
    /** Canonical REST path for the resolved resource, suitable for fetching it directly. */
    canonical_path?: string | undefined;
    /** Lightweight additional context about the resolved entity, such as bulk sync schema_ids. */
    context?: Record<string, unknown> | undefined;
    /** UUID that was resolved. */
    id?: string | undefined;
    /** Organization that owns the resolved resource. Omitted from responses on the user-scoped endpoint. */
    organization_id?: string | undefined;
    /** Parent resources needed to address nested resources, keyed by relationship name (e.g. "sync", "bulk_sync"). */
    relationships?: Record<string, Polytomic.EntityRelationship> | undefined;
    /** Resolved entity type. One of: organization, user, connection, model, sync, sync_execution, bulk_sync, bulk_sync_execution. */
    type?: string | undefined;
}
