// This file was auto-generated by Fern from our API Definition.

export const ExecutionStatus = {
    Created: "created",
    Scheduled: "scheduled",
    Queued: "queued",
    Waiting: "waiting",
    Running: "running",
    Processing: "processing",
    Canceling: "canceling",
    Canceled: "canceled",
    Completed: "completed",
    Failed: "failed",
    Interrupted: "interrupted",
} as const;
export type ExecutionStatus = (typeof ExecutionStatus)[keyof typeof ExecutionStatus];
