/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface GetIdentityResponseSchema {
    email?: string;
    id?: string;
    is_organization?: boolean;
    is_partner?: boolean;
    is_system?: boolean;
    is_user?: boolean;
    organization_id?: string;
    organization_name?: string;
    role?: string;
}
