// This file was auto-generated by Fern from our API Definition.

import type * as Polytomic from "../index";

export interface HarborConnectionListEnvelope {
    data?: Polytomic.HarborConnectionResponse[] | undefined;
    pagination?: Polytomic.PaginationDetails | undefined;
}
