// This file was auto-generated by Fern from our API Definition.

export interface HarborContextMetadataResponse {
    /** When the context document was created. */
    created_at?: string | undefined;
    /** Short summary of the context document. */
    description?: string | undefined;
    /** Unique identifier of the context document. */
    id?: string | undefined;
    /** Exact immutable revision currently published for this context document. */
    revision_id?: string | undefined;
    /** Human-readable context title. */
    title?: string | undefined;
    /** When the context document was last updated. */
    updated_at?: string | undefined;
    /** Current published version number of the context document. */
    version?: number | undefined;
}
