/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The health status of CDC ingestion for a bulk sync. 'ok' means ingestion is operating normally. 'warning' indicates a non-fatal issue. 'error' indicates a potentially fatal ingestion error.
 */
export type IngestionStatusLevel = "ok" | "warning" | "error";
export const IngestionStatusLevel = {
    Ok: "ok",
    Warning: "warning",
    Error: "error",
} as const;
