// This file was auto-generated by Fern from our API Definition.

export interface ModelSyncV5Target {
    configuration?: Record<string, unknown> | undefined;
    connection_id: string;
    /** Create a new target object with these properties. */
    create?: Record<string, string> | undefined;
    /** Deprecated. Use 'target_filters.logic', which combines the conditions it is grouped with. */
    filter_logic?: string | undefined;
    /** Name for a new target object. */
    new_name?: string | undefined;
    object?: string | undefined;
    search_values?: Record<string, unknown> | undefined;
}
