/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface Mode {
    description?: string;
    label?: string;
    mode?: string;
    requires_identity?: boolean;
    supports_field_sync_mode?: boolean;
    supports_target_filters?: boolean;
}
