// This file was auto-generated by Fern from our API Definition.

import type * as Polytomic from "../index";

export interface ModelResponseEnvelope {
    data?: Polytomic.ModelResponse | undefined;
    job?: Polytomic.JobResponse | undefined;
}
