/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Polytomic from "../index";

export interface ModelRelation {
    from?: string;
    to?: Polytomic.ModelRelationTo;
}
