// This file was auto-generated by Fern from our API Definition.

export interface RecordLoggingSettingsResponse {
    /** Blobstorage connection receiving record log deliveries, if one is configured. */
    deliveryConnectionId?: string | undefined;
    /** Name of the destination connection, for display. Omitted when no destination is configured or the connection has been deleted. */
    deliveryConnectionName?: string | undefined;
    /** Path record logs are delivered under, ahead of the organization ID, if one is set. */
    deliveryPrefix?: string | undefined;
    /** True when record logging is enabled for the organization. */
    enabled?: boolean | undefined;
}
