// This file was auto-generated by Fern from our API Definition.

export interface RoleResponse {
    id?: string | undefined;
    name?: string | undefined;
    organization_id?: string | undefined;
    system?: boolean | undefined;
}
