// This file was auto-generated by Fern from our API Definition.

import type * as Polytomic from "../index";

export interface SchemaConfiguration {
    data_cutoff_timestamp?: string | undefined;
    /** Whether data cutoff is disabled for this schema. */
    disable_data_cutoff?: boolean | undefined;
    /** Whether the schema is enabled for syncing. */
    enabled?: boolean | undefined;
    fields?: SchemaConfiguration.Fields.Item[] | undefined;
    filters?: Polytomic.BulkFilter[] | undefined;
    id?: string | undefined;
    partition_key?: string | undefined;
    tracking_field?: string | undefined;
}

export namespace SchemaConfiguration {
    export type Fields = Fields.Item[];

    export namespace Fields {
        export type Item = string | Polytomic.FieldConfiguration;
    }
}
