// This file was auto-generated by Fern from our API Definition.

import type * as Polytomic from "../index";

export interface StartModelSyncResponseEnvelope {
    data?: Polytomic.StartModelSyncResponseSchema | undefined;
}
