// This file was auto-generated by Fern from our API Definition.

import type * as Polytomic from "../index";

export interface SyncCompletedEvent {
    deleted_records?: string[] | undefined;
    error_count?: number | undefined;
    errored_records?: string[] | undefined;
    execution_id?: string | undefined;
    inserted_count?: number | undefined;
    inserted_records?: string[] | undefined;
    organization_id?: string | undefined;
    record_count?: number | undefined;
    status?: Polytomic.ExecutionStatus | undefined;
    sync_id?: string | undefined;
    sync_name?: string | undefined;
    target_connection_id?: string | undefined;
    total_records?: string[] | undefined;
    trigger?: string | undefined;
    updated_count?: number | undefined;
    updated_records?: string[] | undefined;
    upserted_count?: number | undefined;
    warning_count?: number | undefined;
    warnings?: string[] | undefined;
}
