/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Polytomic from "../index";

export interface TargetObject {
    /** The identifier of the target object. */
    id?: string;
    /** The supported sync modes and their properties for the target object. */
    modes?: Polytomic.SupportedMode[];
    /** The name of the target object. */
    name?: string;
}
