/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Polytomic from "../index";

export interface TargetResponse {
    fields?: Polytomic.TargetField[] | null;
    id?: string;
    modes?: Polytomic.Mode[] | null;
    name?: string;
    properties?: Polytomic.SyncDestinationProperties;
    refreshed_at?: string;
}
