// This file was auto-generated by Fern from our API Definition.

/**
 * Detailed field type: a type name such as "bigint", or an array naming a complex type followed by its details, such as ["decimal", {"precision": 10, "scale": 2}] or ["array", "string"].
 */
export type TypesDefinition =
    | "binary"
    | "boolean"
    | "date"
    | "datetime"
    | "datetime_tz"
    | "time"
    | "number"
    | "string"
    | "smallint"
    | "int"
    | "bigint"
    | "single"
    | "double"
    | unknown[];
