/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Similar to a model configuration, this configures the enricher. For example, if you wanted to use Apollo to enrich people, you would send `{"object": "people"}` as the configuration. Each enricher configuration can be found in the connection configuration docs.
 */
export type V2EnricherConfiguration = Record<string, unknown>;
