// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseIdempotentRequestOptions, BaseRequestOptions } from "../../../../BaseClient";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient";
import * as core from "../../../../core";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers";
import * as environments from "../../../../environments";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError";
import * as errors from "../../../../errors/index";
import * as Polytomic from "../../../index";

export declare namespace WebhooksClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}

    export interface IdempotentRequestOptions extends RequestOptions, BaseIdempotentRequestOptions {}
}

export class WebhooksClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<WebhooksClient.Options>;

    constructor(options: WebhooksClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * Lists the webhooks for the caller's organization.
     *
     * > 📘 One webhook per organization
     * >
     * > An organization can register a single webhook, which receives every event
     * > produced in that organization. See the
     * > [Events documentation](../../guides/events) for the
     * > list of event types and payload shapes.
     *
     * @param {WebhooksClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Polytomic.InternalServerError}
     *
     * @example
     *     await client.webhooks.list()
     */
    public list(
        requestOptions?: WebhooksClient.RequestOptions,
    ): core.HttpResponsePromise<Polytomic.WebhookListEnvelope> {
        return core.HttpResponsePromise.fromPromise(this.__list(requestOptions));
    }

    private async __list(
        requestOptions?: WebhooksClient.RequestOptions,
    ): Promise<core.WithRawResponse<Polytomic.WebhookListEnvelope>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "X-Polytomic-Version": requestOptions?.version ?? this._options?.version ?? "2025-09-18",
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PolytomicEnvironment.Default,
                "api/webhooks",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Polytomic.WebhookListEnvelope, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 500:
                    throw new Polytomic.InternalServerError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.PolytomicError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/api/webhooks");
    }

    /**
     * Creates the organization's webhook.
     *
     * > 📘 One webhook per organization
     * >
     * > An organization can register a single webhook, which receives every event
     * > produced in that organization. See the
     * > [Events documentation](../../guides/events) for the
     * > list of event types and payload shapes.
     *
     * @param {Polytomic.CreateWebhooksSchema} request
     * @param {WebhooksClient.IdempotentRequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Polytomic.UnauthorizedError}
     * @throws {@link Polytomic.UnprocessableEntityError}
     * @throws {@link Polytomic.InternalServerError}
     *
     * @example
     *     await client.webhooks.create({
     *         endpoint: "https://example.com/webhook",
     *         secret: "secret"
     *     })
     */
    public create(
        request: Polytomic.CreateWebhooksSchema,
        requestOptions?: WebhooksClient.IdempotentRequestOptions,
    ): core.HttpResponsePromise<Polytomic.WebhookEnvelope> {
        return core.HttpResponsePromise.fromPromise(this.__create(request, requestOptions));
    }

    private async __create(
        request: Polytomic.CreateWebhooksSchema,
        requestOptions?: WebhooksClient.IdempotentRequestOptions,
    ): Promise<core.WithRawResponse<Polytomic.WebhookEnvelope>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "Idempotency-Key": requestOptions?.idempotencyKey,
                "X-Polytomic-Version": requestOptions?.version ?? this._options?.version ?? "2025-09-18",
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PolytomicEnvironment.Default,
                "api/webhooks",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Polytomic.WebhookEnvelope, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Polytomic.UnauthorizedError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                case 422:
                    throw new Polytomic.UnprocessableEntityError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Polytomic.InternalServerError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.PolytomicError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/api/webhooks");
    }

    /**
     * Returns a single webhook by ID.
     *
     * > 📘 One webhook per organization
     * >
     * > An organization can register a single webhook, which receives every event
     * > produced in that organization. See the
     * > [Events documentation](../../../guides/events) for the
     * > list of event types and payload shapes.
     *
     * @param {string} id
     * @param {WebhooksClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Polytomic.NotFoundError}
     *
     * @example
     *     await client.webhooks.get("248df4b7-aa70-47b8-a036-33ac447e668d")
     */
    public get(
        id: string,
        requestOptions?: WebhooksClient.RequestOptions,
    ): core.HttpResponsePromise<Polytomic.WebhookEnvelope> {
        return core.HttpResponsePromise.fromPromise(this.__get(id, requestOptions));
    }

    private async __get(
        id: string,
        requestOptions?: WebhooksClient.RequestOptions,
    ): Promise<core.WithRawResponse<Polytomic.WebhookEnvelope>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "X-Polytomic-Version": requestOptions?.version ?? this._options?.version ?? "2025-09-18",
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PolytomicEnvironment.Default,
                `api/webhooks/${core.url.encodePathParam(id)}`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Polytomic.WebhookEnvelope, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new Polytomic.NotFoundError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.PolytomicError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/api/webhooks/{id}");
    }

    /**
     * Updates an existing webhook.
     *
     * > 📘 One webhook per organization
     * >
     * > An organization can register a single webhook, which receives every event
     * > produced in that organization. See the
     * > [Events documentation](../../../guides/events) for the
     * > list of event types and payload shapes.
     *
     * @param {string} id
     * @param {Polytomic.UpdateWebhooksSchema} request
     * @param {WebhooksClient.IdempotentRequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Polytomic.UnauthorizedError}
     * @throws {@link Polytomic.UnprocessableEntityError}
     * @throws {@link Polytomic.InternalServerError}
     *
     * @example
     *     await client.webhooks.update("248df4b7-aa70-47b8-a036-33ac447e668d", {
     *         endpoint: "https://example.com/webhook",
     *         secret: "secret"
     *     })
     */
    public update(
        id: string,
        request: Polytomic.UpdateWebhooksSchema,
        requestOptions?: WebhooksClient.IdempotentRequestOptions,
    ): core.HttpResponsePromise<Polytomic.WebhookEnvelope> {
        return core.HttpResponsePromise.fromPromise(this.__update(id, request, requestOptions));
    }

    private async __update(
        id: string,
        request: Polytomic.UpdateWebhooksSchema,
        requestOptions?: WebhooksClient.IdempotentRequestOptions,
    ): Promise<core.WithRawResponse<Polytomic.WebhookEnvelope>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "Idempotency-Key": requestOptions?.idempotencyKey,
                "X-Polytomic-Version": requestOptions?.version ?? this._options?.version ?? "2025-09-18",
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PolytomicEnvironment.Default,
                `api/webhooks/${core.url.encodePathParam(id)}`,
            ),
            method: "PUT",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Polytomic.WebhookEnvelope, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Polytomic.UnauthorizedError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                case 422:
                    throw new Polytomic.UnprocessableEntityError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Polytomic.InternalServerError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.PolytomicError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "PUT", "/api/webhooks/{id}");
    }

    /**
     * Deletes a webhook.
     *
     * > 📘 One webhook per organization
     * >
     * > An organization can register a single webhook, which receives every event
     * > produced in that organization. See the
     * > [Events documentation](../../../guides/events) for the
     * > list of event types and payload shapes.
     *
     * Deletion is permanent. To stop delivery without losing the webhook
     * configuration, use
     * [`POST /api/webhooks/{id}/disable`](../../../api-reference/webhooks/disable) instead.
     *
     * @param {string} id
     * @param {WebhooksClient.IdempotentRequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Polytomic.NotFoundError}
     * @throws {@link Polytomic.InternalServerError}
     *
     * @example
     *     await client.webhooks.remove("248df4b7-aa70-47b8-a036-33ac447e668d")
     */
    public remove(
        id: string,
        requestOptions?: WebhooksClient.IdempotentRequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__remove(id, requestOptions));
    }

    private async __remove(
        id: string,
        requestOptions?: WebhooksClient.IdempotentRequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "Idempotency-Key": requestOptions?.idempotencyKey,
                "X-Polytomic-Version": requestOptions?.version ?? this._options?.version ?? "2025-09-18",
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PolytomicEnvironment.Default,
                `api/webhooks/${core.url.encodePathParam(id)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new Polytomic.NotFoundError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Polytomic.InternalServerError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.PolytomicError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "DELETE", "/api/webhooks/{id}");
    }

    /**
     * Disables a webhook without deleting it.
     *
     * > 📘 One webhook per organization
     * >
     * > An organization can register a single webhook, which receives every event
     * > produced in that organization. See the
     * > [Events documentation](../../../../guides/events) for the
     * > list of event types and payload shapes.
     *
     * Events are not queued while the webhook is disabled — any activity that occurs
     * during the disabled period is not delivered retroactively. To resume
     * delivery, re-enable the webhook using
     * [`POST /api/webhooks/{id}/enable`](../../../../api-reference/webhooks/enable).
     *
     * @param {string} id
     * @param {WebhooksClient.IdempotentRequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Polytomic.UnauthorizedError}
     * @throws {@link Polytomic.NotFoundError}
     * @throws {@link Polytomic.InternalServerError}
     *
     * @example
     *     await client.webhooks.disable("248df4b7-aa70-47b8-a036-33ac447e668d")
     */
    public disable(
        id: string,
        requestOptions?: WebhooksClient.IdempotentRequestOptions,
    ): core.HttpResponsePromise<Polytomic.WebhookEnvelope> {
        return core.HttpResponsePromise.fromPromise(this.__disable(id, requestOptions));
    }

    private async __disable(
        id: string,
        requestOptions?: WebhooksClient.IdempotentRequestOptions,
    ): Promise<core.WithRawResponse<Polytomic.WebhookEnvelope>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "Idempotency-Key": requestOptions?.idempotencyKey,
                "X-Polytomic-Version": requestOptions?.version ?? this._options?.version ?? "2025-09-18",
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PolytomicEnvironment.Default,
                `api/webhooks/${core.url.encodePathParam(id)}/disable`,
            ),
            method: "POST",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Polytomic.WebhookEnvelope, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Polytomic.UnauthorizedError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Polytomic.NotFoundError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Polytomic.InternalServerError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.PolytomicError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/api/webhooks/{id}/disable");
    }

    /**
     * Re-enables a previously disabled webhook.
     *
     * > 📘 One webhook per organization
     * >
     * > An organization can register a single webhook, which receives every event
     * > produced in that organization. See the
     * > [Events documentation](../../../../guides/events) for the
     * > list of event types and payload shapes.
     *
     * Delivery resumes from the next event generated after this call. Events that
     * occurred while the webhook was disabled are not replayed.
     *
     * @param {string} id
     * @param {WebhooksClient.IdempotentRequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Polytomic.UnauthorizedError}
     * @throws {@link Polytomic.NotFoundError}
     * @throws {@link Polytomic.InternalServerError}
     *
     * @example
     *     await client.webhooks.enable("248df4b7-aa70-47b8-a036-33ac447e668d")
     */
    public enable(
        id: string,
        requestOptions?: WebhooksClient.IdempotentRequestOptions,
    ): core.HttpResponsePromise<Polytomic.WebhookEnvelope> {
        return core.HttpResponsePromise.fromPromise(this.__enable(id, requestOptions));
    }

    private async __enable(
        id: string,
        requestOptions?: WebhooksClient.IdempotentRequestOptions,
    ): Promise<core.WithRawResponse<Polytomic.WebhookEnvelope>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "Idempotency-Key": requestOptions?.idempotencyKey,
                "X-Polytomic-Version": requestOptions?.version ?? this._options?.version ?? "2025-09-18",
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PolytomicEnvironment.Default,
                `api/webhooks/${core.url.encodePathParam(id)}/enable`,
            ),
            method: "POST",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Polytomic.WebhookEnvelope, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Polytomic.UnauthorizedError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Polytomic.NotFoundError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Polytomic.InternalServerError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.PolytomicError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/api/webhooks/{id}/enable");
    }
}
