// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseIdempotentRequestOptions, BaseRequestOptions } from "../../../../../../BaseClient";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../../../BaseClient";
import * as core from "../../../../../../core";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../../../core/headers";
import { toJson } from "../../../../../../core/json";
import * as environments from "../../../../../../environments";
import { handleNonStatusCodeError } from "../../../../../../errors/handleNonStatusCodeError";
import * as errors from "../../../../../../errors/index";
import * as Polytomic from "../../../../../index";

export declare namespace SchemasClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}

    export interface IdempotentRequestOptions extends RequestOptions, BaseIdempotentRequestOptions {}
}

export class SchemasClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<SchemasClient.Options>;

    constructor(options: SchemasClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * Lists the schemas (tables, objects) configured for a bulk sync.
     *
     * This endpoint returns the schemas that have been added to and configured on this
     * specific bulk sync — not the full set of schemas available from the source
     * connection. To discover what the source connection exposes, use the source
     * schemas endpoint for the relevant connection type.
     *
     * Each schema in the response includes its sync mode, field selections, and any
     * custom configuration applied via
     * [`PATCH /api/bulk/syncs/{id}/schemas`](../../../../../api-reference/bulk-sync/schemas/patch)
     * or
     * [`PUT /api/bulk/syncs/{id}/schemas/{schema_id}`](../../../../../api-reference/bulk-sync/schemas/update).
     *
     * @param {string} id - Unique identifier of the bulk sync.
     * @param {Polytomic.bulkSync.SchemasListRequest} request
     * @param {SchemasClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Polytomic.NotFoundError}
     *
     * @example
     *     await client.bulkSync.schemas.list("248df4b7-aa70-47b8-a036-33ac447e668d")
     */
    public list(
        id: string,
        request: Polytomic.bulkSync.SchemasListRequest = {},
        requestOptions?: SchemasClient.RequestOptions,
    ): core.HttpResponsePromise<Polytomic.ListBulkSchemaEnvelope> {
        return core.HttpResponsePromise.fromPromise(this.__list(id, request, requestOptions));
    }

    private async __list(
        id: string,
        request: Polytomic.bulkSync.SchemasListRequest = {},
        requestOptions?: SchemasClient.RequestOptions,
    ): Promise<core.WithRawResponse<Polytomic.ListBulkSchemaEnvelope>> {
        const { filters } = request;
        const _queryParams: Record<string, unknown> = {
            filters: filters != null ? toJson(filters) : undefined,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "X-Polytomic-Version": requestOptions?.version ?? this._options?.version ?? "2025-09-18",
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PolytomicEnvironment.Default,
                `api/bulk/syncs/${core.url.encodePathParam(id)}/schemas`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Polytomic.ListBulkSchemaEnvelope, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new Polytomic.NotFoundError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.PolytomicError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/api/bulk/syncs/{id}/schemas");
    }

    /**
     * Patches one or more schemas on a bulk sync at once.
     *
     * Only schemas explicitly included in the request body are modified; schemas
     * omitted from the request are left unchanged. This makes PATCH the right choice
     * when you want to update a subset of tables without affecting the rest of the
     * sync's schema configuration.
     *
     * Within each provided schema, omitting `fields` enables all available fields on
     * that schema. To control which fields are enabled, include the `fields` array
     * with explicit `enabled` values for each field.
     *
     * > 📘 To replace a single schema's configuration in full (clearing any fields you
     * > omit), use
     * > [`PUT /api/bulk/syncs/{id}/schemas/{schema_id}`](../../../../../api-reference/bulk-sync/schemas/update)
     * > instead.
     *
     * @param {string} id - Unique identifier of the bulk sync.
     * @param {Polytomic.bulkSync.UpdateBulkSyncSchemasRequest} request
     * @param {SchemasClient.IdempotentRequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Polytomic.BadRequestError}
     * @throws {@link Polytomic.ForbiddenError}
     * @throws {@link Polytomic.NotFoundError}
     * @throws {@link Polytomic.InternalServerError}
     *
     * @example
     *     await client.bulkSync.schemas.patch("248df4b7-aa70-47b8-a036-33ac447e668d")
     */
    public patch(
        id: string,
        request: Polytomic.bulkSync.UpdateBulkSyncSchemasRequest = {},
        requestOptions?: SchemasClient.IdempotentRequestOptions,
    ): core.HttpResponsePromise<Polytomic.UpdateBulkSyncSchemasEnvelope> {
        return core.HttpResponsePromise.fromPromise(this.__patch(id, request, requestOptions));
    }

    private async __patch(
        id: string,
        request: Polytomic.bulkSync.UpdateBulkSyncSchemasRequest = {},
        requestOptions?: SchemasClient.IdempotentRequestOptions,
    ): Promise<core.WithRawResponse<Polytomic.UpdateBulkSyncSchemasEnvelope>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "Idempotency-Key": requestOptions?.idempotencyKey,
                "X-Polytomic-Version": requestOptions?.version ?? this._options?.version ?? "2025-09-18",
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PolytomicEnvironment.Default,
                `api/bulk/syncs/${core.url.encodePathParam(id)}/schemas`,
            ),
            method: "PATCH",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as Polytomic.UpdateBulkSyncSchemasEnvelope,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Polytomic.BadRequestError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Polytomic.ForbiddenError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Polytomic.NotFoundError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Polytomic.InternalServerError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.PolytomicError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "PATCH",
            "/api/bulk/syncs/{id}/schemas",
        );
    }

    /**
     * Returns the configuration of a single schema on a bulk sync.
     *
     * Returns the sync mode, field selections, and any other configuration applied to
     * this schema on the bulk sync.
     *
     * To modify the configuration, use
     * [`PATCH /api/bulk/syncs/{id}/schemas`](../../../../../../api-reference/bulk-sync/schemas/patch)
     * for a partial update across multiple schemas, or
     * [`PUT /api/bulk/syncs/{id}/schemas/{schema_id}`](../../../../../../api-reference/bulk-sync/schemas/update)
     * to fully replace this schema's configuration.
     *
     * @param {string} id - Unique identifier of the bulk sync.
     * @param {string} schema_id - Source-side schema identifier.
     * @param {SchemasClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Polytomic.NotFoundError}
     *
     * @example
     *     await client.bulkSync.schemas.get("248df4b7-aa70-47b8-a036-33ac447e668d", "Contact")
     */
    public get(
        id: string,
        schema_id: string,
        requestOptions?: SchemasClient.RequestOptions,
    ): core.HttpResponsePromise<Polytomic.BulkSchemaEnvelope> {
        return core.HttpResponsePromise.fromPromise(this.__get(id, schema_id, requestOptions));
    }

    private async __get(
        id: string,
        schema_id: string,
        requestOptions?: SchemasClient.RequestOptions,
    ): Promise<core.WithRawResponse<Polytomic.BulkSchemaEnvelope>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "X-Polytomic-Version": requestOptions?.version ?? this._options?.version ?? "2025-09-18",
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PolytomicEnvironment.Default,
                `api/bulk/syncs/${core.url.encodePathParam(id)}/schemas/${core.url.encodePathParam(schema_id)}`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Polytomic.BulkSchemaEnvelope, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new Polytomic.NotFoundError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.PolytomicError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/api/bulk/syncs/{id}/schemas/{schema_id}",
        );
    }

    /**
     * Replaces the configuration of a single schema on a bulk sync.
     *
     * This is a full replacement: every field in the request body is written to the
     * schema, and any field you omit is cleared or reset to its default. Fetch the
     * current configuration with
     * [`GET /api/bulk/syncs/{id}/schemas/{schema_id}`](../../../../../../api-reference/bulk-sync/schemas/get)
     * first if you want to preserve existing settings while changing only a subset.
     *
     * Omitting `fields` enables all available fields on the schema. To control which
     * fields are enabled, include the `fields` array with explicit `enabled` values.
     *
     * > 📘 To update multiple schemas in a single request without affecting others,
     * > use the partial-update endpoint
     * > [`PATCH /api/bulk/syncs/{id}/schemas`](../../../../../../api-reference/bulk-sync/schemas/patch)
     * > instead.
     *
     * @param {string} id - Unique identifier of the bulk sync.
     * @param {string} schema_id - Source-side schema identifier.
     * @param {Polytomic.bulkSync.UpdateBulkSchema} request
     * @param {SchemasClient.IdempotentRequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Polytomic.ForbiddenError}
     * @throws {@link Polytomic.NotFoundError}
     * @throws {@link Polytomic.InternalServerError}
     *
     * @example
     *     await client.bulkSync.schemas.update("248df4b7-aa70-47b8-a036-33ac447e668d", "contact")
     */
    public update(
        id: string,
        schema_id: string,
        request: Polytomic.bulkSync.UpdateBulkSchema = {},
        requestOptions?: SchemasClient.IdempotentRequestOptions,
    ): core.HttpResponsePromise<Polytomic.BulkSchemaEnvelope> {
        return core.HttpResponsePromise.fromPromise(this.__update(id, schema_id, request, requestOptions));
    }

    private async __update(
        id: string,
        schema_id: string,
        request: Polytomic.bulkSync.UpdateBulkSchema = {},
        requestOptions?: SchemasClient.IdempotentRequestOptions,
    ): Promise<core.WithRawResponse<Polytomic.BulkSchemaEnvelope>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "Idempotency-Key": requestOptions?.idempotencyKey,
                "X-Polytomic-Version": requestOptions?.version ?? this._options?.version ?? "2025-09-18",
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PolytomicEnvironment.Default,
                `api/bulk/syncs/${core.url.encodePathParam(id)}/schemas/${core.url.encodePathParam(schema_id)}`,
            ),
            method: "PUT",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Polytomic.BulkSchemaEnvelope, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 403:
                    throw new Polytomic.ForbiddenError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Polytomic.NotFoundError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Polytomic.InternalServerError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.PolytomicError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "PUT",
            "/api/bulk/syncs/{id}/schemas/{schema_id}",
        );
    }

    /**
     * Requests cancellation of any running executions for a specific schema on a bulk sync.
     *
     * Cancellation is asynchronous. A successful response means the cancellation
     * signal for this schema has been queued; the schema's in-flight work continues
     * until the signal is processed. Poll
     * `GET /api/bulk/syncs/{id}/schemas/{schema_id}` and the parent execution via
     * `GET /api/bulk/syncs/{id}/status` to confirm the schema has reached a terminal
     * state.
     *
     * @param {string} id - The bulk sync ID.
     * @param {string} schema_id - The schema ID to cancel for the bulk sync.
     * @param {SchemasClient.IdempotentRequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Polytomic.ForbiddenError}
     * @throws {@link Polytomic.NotFoundError}
     * @throws {@link Polytomic.InternalServerError}
     *
     * @example
     *     await client.bulkSync.schemas.cancel("248df4b7-aa70-47b8-a036-33ac447e668d", "schema_id")
     */
    public cancel(
        id: string,
        schema_id: string,
        requestOptions?: SchemasClient.IdempotentRequestOptions,
    ): core.HttpResponsePromise<Polytomic.CancelBulkSyncResponseEnvelope> {
        return core.HttpResponsePromise.fromPromise(this.__cancel(id, schema_id, requestOptions));
    }

    private async __cancel(
        id: string,
        schema_id: string,
        requestOptions?: SchemasClient.IdempotentRequestOptions,
    ): Promise<core.WithRawResponse<Polytomic.CancelBulkSyncResponseEnvelope>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "Idempotency-Key": requestOptions?.idempotencyKey,
                "X-Polytomic-Version": requestOptions?.version ?? this._options?.version ?? "2025-09-18",
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PolytomicEnvironment.Default,
                `api/bulk/syncs/${core.url.encodePathParam(id)}/schemas/${core.url.encodePathParam(schema_id)}/cancel`,
            ),
            method: "POST",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as Polytomic.CancelBulkSyncResponseEnvelope,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 403:
                    throw new Polytomic.ForbiddenError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Polytomic.NotFoundError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Polytomic.InternalServerError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.PolytomicError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/api/bulk/syncs/{id}/schemas/{schema_id}/cancel",
        );
    }
}
