// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions } from "../../../../BaseClient";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient";
import { PoliciesClient } from "../resources/policies/client/Client";
import { RolesClient } from "../resources/roles/client/Client";

export declare namespace PermissionsClient {
    export type Options = BaseClientOptions;
}

export class PermissionsClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<PermissionsClient.Options>;
    protected _policies: PoliciesClient | undefined;
    protected _roles: RolesClient | undefined;

    constructor(options: PermissionsClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get policies(): PoliciesClient {
        return (this._policies ??= new PoliciesClient(this._options));
    }

    public get roles(): RolesClient {
        return (this._roles ??= new RolesClient(this._options));
    }
}
