"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.V2CreateSyncRequestMode = void 0;
exports.V2CreateSyncRequestMode = {
    Update: "update",
    UpdateOrCreate: "updateOrCreate",
    Create: "create",
    Replace: "replace",
    Append: "append",
    Snapshot: "snapshot",
};
