/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as environments from "../../../../environments";
import * as core from "../../../../core";
import * as PolytomicApi from "../../..";
export declare namespace Events {
    interface Options {
        environment?: core.Supplier<environments.PolytomicApiEnvironment | string>;
        token: core.Supplier<core.BearerToken>;
    }
    interface RequestOptions {
        timeoutInSeconds?: number;
    }
}
export declare class Events {
    protected readonly _options: Events.Options;
    constructor(_options: Events.Options);
    /**
     * @throws {@link PolytomicApi.UnauthorizedError}
     */
    apiV2GetEvents(request?: PolytomicApi.ApiV2GetEventsRequest, requestOptions?: Events.RequestOptions): Promise<PolytomicApi.V2EventsEnvelope>;
    /**
     * @throws {@link PolytomicApi.UnauthorizedError}
     */
    apiV2GetEventTypes(requestOptions?: Events.RequestOptions): Promise<PolytomicApi.V2EventTypesEnvelope>;
    protected _getAuthorizationHeader(): Promise<string>;
}
