"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.PolytomicApiTimeoutError = void 0;
class PolytomicApiTimeoutError extends Error {
    constructor() {
        super("Timeout");
        Object.setPrototypeOf(this, PolytomicApiTimeoutError.prototype);
    }
}
exports.PolytomicApiTimeoutError = PolytomicApiTimeoutError;
