/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         page: "page"
 *     }
 */
export interface QueryRunnerGetQueryRequest {
    /**
     * Opaque pagination token returned in the links.next or links.previous URL of the previous response.
     */
    page?: string;
}
