// This file was auto-generated by Fern from our API Definition.

import * as Polytomic from "../../src/api/index";
import { PolytomicClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("EntitiesClient", () => {
    test("Get (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PolytomicClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            data: {
                canonical_path:
                    "/api/syncs/0ecd09c1-b901-4d27-9053-f0367c427254/executions/8f63fd67-5d47-4cb2-a5fc-e8b933799065",
                context: { key: "value" },
                id: "248df4b7-aa70-47b8-a036-33ac447e668d",
                organization_id: "248df4b7-aa70-47b8-a036-33ac447e668d",
                relationships: {
                    key: {
                        id: "248df4b7-aa70-47b8-a036-33ac447e668d",
                        path: "/api/syncs/0ecd09c1-b901-4d27-9053-f0367c427254",
                    },
                },
                type: "sync_execution",
            },
        };

        server
            .mockEndpoint()
            .get("/api/entities/248df4b7-aa70-47b8-a036-33ac447e668d")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.entities.get("248df4b7-aa70-47b8-a036-33ac447e668d");
        expect(response).toEqual(rawResponseBody);
    });

    test("Get (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PolytomicClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {};

        server.mockEndpoint().get("/api/entities/id").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.entities.get("id");
        }).rejects.toThrow(Polytomic.UnauthorizedError);
    });

    test("Get (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PolytomicClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {};

        server.mockEndpoint().get("/api/entities/id").respondWith().statusCode(403).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.entities.get("id");
        }).rejects.toThrow(Polytomic.ForbiddenError);
    });

    test("Get (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new PolytomicClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {};

        server.mockEndpoint().get("/api/entities/id").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.entities.get("id");
        }).rejects.toThrow(Polytomic.NotFoundError);
    });

    test("Get (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new PolytomicClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {};

        server.mockEndpoint().get("/api/entities/id").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.entities.get("id");
        }).rejects.toThrow(Polytomic.InternalServerError);
    });

    test("GetForPartner (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PolytomicClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            data: {
                canonical_path:
                    "/api/syncs/0ecd09c1-b901-4d27-9053-f0367c427254/executions/8f63fd67-5d47-4cb2-a5fc-e8b933799065",
                context: { key: "value" },
                id: "248df4b7-aa70-47b8-a036-33ac447e668d",
                organization_id: "248df4b7-aa70-47b8-a036-33ac447e668d",
                relationships: {
                    key: {
                        id: "248df4b7-aa70-47b8-a036-33ac447e668d",
                        path: "/api/syncs/0ecd09c1-b901-4d27-9053-f0367c427254",
                    },
                },
                type: "sync_execution",
            },
        };

        server
            .mockEndpoint()
            .get("/api/organizations/entities/248df4b7-aa70-47b8-a036-33ac447e668d")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.entities.getForPartner("248df4b7-aa70-47b8-a036-33ac447e668d");
        expect(response).toEqual(rawResponseBody);
    });

    test("GetForPartner (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PolytomicClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/organizations/entities/id")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.entities.getForPartner("id");
        }).rejects.toThrow(Polytomic.ForbiddenError);
    });

    test("GetForPartner (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PolytomicClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/organizations/entities/id")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.entities.getForPartner("id");
        }).rejects.toThrow(Polytomic.NotFoundError);
    });

    test("GetForPartner (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new PolytomicClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/organizations/entities/id")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.entities.getForPartner("id");
        }).rejects.toThrow(Polytomic.InternalServerError);
    });
});
