// This file was auto-generated by Fern from our API Definition.

import * as Polytomic from "../../src/api/index";
import { PolytomicClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("EventsClient", () => {
    test("List (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PolytomicClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            data: [
                {
                    created_at: "2024-01-01T00:00:00Z",
                    event: {
                        execution_id: "248df4b7-aa70-47b8-a036-33ac447e668d",
                        organization_id: "248df4b7-aa70-47b8-a036-33ac447e668d",
                        sync_id: "248df4b7-aa70-47b8-a036-33ac447e668d",
                        target_connection_id: "248df4b7-aa70-47b8-a036-33ac447e668d",
                    },
                    id: "248df4b7-aa70-47b8-a036-33ac447e668d",
                    organization_id: "248df4b7-aa70-47b8-a036-33ac447e668d",
                    type: "sync.running",
                },
            ],
        };

        server.mockEndpoint().get("/api/events").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.events.list({
            organization_id: "248df4b7-aa70-47b8-a036-33ac447e668d",
            type: "type",
            starting_after: "2020-01-01T00:00:00Z",
            ending_before: "2020-01-01T00:00:00Z",
            limit: 1,
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("List (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PolytomicClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {};

        server.mockEndpoint().get("/api/events").respondWith().statusCode(422).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.events.list();
        }).rejects.toThrow(Polytomic.UnprocessableEntityError);
    });

    test("List (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PolytomicClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {};

        server.mockEndpoint().get("/api/events").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.events.list();
        }).rejects.toThrow(Polytomic.InternalServerError);
    });

    test("GetTypes", async () => {
        const server = mockServerPool.createServer();
        const client = new PolytomicClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { data: ["data"] };

        server.mockEndpoint().get("/api/events_types").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.events.getTypes();
        expect(response).toEqual(rawResponseBody);
    });
});
