// This file was auto-generated by Fern from our API Definition.

import * as Polytomic from "../../src/api/index";
import { PolytomicClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("IdentityClient", () => {
    test("Get (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PolytomicClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            data: {
                email: "mail@example.com",
                id: "248df4b7-aa70-47b8-a036-33ac447e668d",
                is_organization: false,
                is_partner: false,
                is_system: false,
                is_user: true,
                organization_id: "248df4b7-aa70-47b8-a036-33ac447e668d",
                organization_name: "My Organization",
            },
        };

        server.mockEndpoint().get("/api/me").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.identity.get();
        expect(response).toEqual(rawResponseBody);
    });

    test("Get (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PolytomicClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {};

        server.mockEndpoint().get("/api/me").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.identity.get();
        }).rejects.toThrow(Polytomic.UnauthorizedError);
    });

    test("Get (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PolytomicClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {};

        server.mockEndpoint().get("/api/me").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.identity.get();
        }).rejects.toThrow(Polytomic.InternalServerError);
    });
});
