// This file was auto-generated by Fern from our API Definition.

import * as Polytomic from "../../src/api/index";
import { PolytomicClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("OrganizationClient", () => {
    test("List (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PolytomicClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            data: [
                {
                    id: "id",
                    issuer: "https://example.com",
                    name: "My Organization",
                    sso_domain: "example.com",
                    sso_org_id: "123456",
                },
            ],
        };

        server.mockEndpoint().get("/api/organizations").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.organization.list();
        expect(response).toEqual({
            data: [
                {
                    id: "id",
                    issuer: "https://example.com",
                    name: "My Organization",
                    sso_domain: "example.com",
                    sso_org_id: "123456",
                },
            ],
        });
    });

    test("List (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PolytomicClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {};

        server.mockEndpoint().get("/api/organizations").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.organization.list();
        }).rejects.toThrow(Polytomic.UnauthorizedError);
    });

    test("List (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PolytomicClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {};

        server.mockEndpoint().get("/api/organizations").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.organization.list();
        }).rejects.toThrow(Polytomic.InternalServerError);
    });

    test("Create (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PolytomicClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "My Organization" };
        const rawResponseBody = {
            data: {
                id: "id",
                issuer: "https://example.com",
                name: "My Organization",
                sso_domain: "example.com",
                sso_org_id: "123456",
            },
        };

        server
            .mockEndpoint()
            .post("/api/organizations")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.organization.create({
            name: "My Organization",
        });
        expect(response).toEqual({
            data: {
                id: "id",
                issuer: "https://example.com",
                name: "My Organization",
                sso_domain: "example.com",
                sso_org_id: "123456",
            },
        });
    });

    test("Create (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PolytomicClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/api/organizations")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.organization.create({
                name: "name",
            });
        }).rejects.toThrow(Polytomic.UnauthorizedError);
    });

    test("Create (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PolytomicClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/api/organizations")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.organization.create({
                name: "name",
            });
        }).rejects.toThrow(Polytomic.ConflictError);
    });

    test("Create (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new PolytomicClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/api/organizations")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.organization.create({
                name: "name",
            });
        }).rejects.toThrow(Polytomic.UnprocessableEntityError);
    });

    test("Create (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new PolytomicClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/api/organizations")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.organization.create({
                name: "name",
            });
        }).rejects.toThrow(Polytomic.InternalServerError);
    });

    test("Get (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PolytomicClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            data: {
                id: "id",
                issuer: "https://example.com",
                name: "My Organization",
                sso_domain: "example.com",
                sso_org_id: "123456",
            },
        };

        server
            .mockEndpoint()
            .get("/api/organizations/248df4b7-aa70-47b8-a036-33ac447e668d")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.organization.get("248df4b7-aa70-47b8-a036-33ac447e668d");
        expect(response).toEqual({
            data: {
                id: "id",
                issuer: "https://example.com",
                name: "My Organization",
                sso_domain: "example.com",
                sso_org_id: "123456",
            },
        });
    });

    test("Get (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PolytomicClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/organizations/id")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.organization.get("id");
        }).rejects.toThrow(Polytomic.UnauthorizedError);
    });

    test("Get (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PolytomicClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/organizations/id")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.organization.get("id");
        }).rejects.toThrow(Polytomic.ForbiddenError);
    });

    test("Get (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new PolytomicClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/organizations/id")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.organization.get("id");
        }).rejects.toThrow(Polytomic.NotFoundError);
    });

    test("Update (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PolytomicClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "My Organization" };
        const rawResponseBody = {
            data: {
                id: "id",
                issuer: "https://example.com",
                name: "My Organization",
                sso_domain: "example.com",
                sso_org_id: "123456",
            },
        };

        server
            .mockEndpoint()
            .put("/api/organizations/248df4b7-aa70-47b8-a036-33ac447e668d")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.organization.update("248df4b7-aa70-47b8-a036-33ac447e668d", {
            name: "My Organization",
        });
        expect(response).toEqual({
            data: {
                id: "id",
                issuer: "https://example.com",
                name: "My Organization",
                sso_domain: "example.com",
                sso_org_id: "123456",
            },
        });
    });

    test("Update (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PolytomicClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .put("/api/organizations/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.organization.update("id", {
                name: "name",
            });
        }).rejects.toThrow(Polytomic.UnauthorizedError);
    });

    test("Update (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PolytomicClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .put("/api/organizations/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.organization.update("id", {
                name: "name",
            });
        }).rejects.toThrow(Polytomic.ForbiddenError);
    });

    test("Update (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new PolytomicClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .put("/api/organizations/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.organization.update("id", {
                name: "name",
            });
        }).rejects.toThrow(Polytomic.ConflictError);
    });

    test("Update (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new PolytomicClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .put("/api/organizations/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.organization.update("id", {
                name: "name",
            });
        }).rejects.toThrow(Polytomic.UnprocessableEntityError);
    });

    test("Update (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new PolytomicClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .put("/api/organizations/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.organization.update("id", {
                name: "name",
            });
        }).rejects.toThrow(Polytomic.InternalServerError);
    });

    test("Remove (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PolytomicClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        server
            .mockEndpoint()
            .delete("/api/organizations/248df4b7-aa70-47b8-a036-33ac447e668d")
            .respondWith()
            .statusCode(200)
            .build();

        const response = await client.organization.remove("248df4b7-aa70-47b8-a036-33ac447e668d");
        expect(response).toEqual(undefined);
    });

    test("Remove (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PolytomicClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .delete("/api/organizations/id")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.organization.remove("id");
        }).rejects.toThrow(Polytomic.UnauthorizedError);
    });

    test("Remove (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PolytomicClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .delete("/api/organizations/id")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.organization.remove("id");
        }).rejects.toThrow(Polytomic.ForbiddenError);
    });

    test("Remove (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new PolytomicClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .delete("/api/organizations/id")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.organization.remove("id");
        }).rejects.toThrow(Polytomic.NotFoundError);
    });

    test("Remove (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new PolytomicClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .delete("/api/organizations/id")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.organization.remove("id");
        }).rejects.toThrow(Polytomic.InternalServerError);
    });
});
