// This file was auto-generated by Fern from our API Definition.

import * as Polytomic from "../../src/api/index";
import { PolytomicClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("WebhooksClient", () => {
    test("List (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PolytomicClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            data: [
                {
                    created_at: "2024-01-01T00:00:00Z",
                    disabled: true,
                    endpoint: "https://example.com/webhook",
                    id: "248df4b7-aa70-47b8-a036-33ac447e668d",
                    organization_id: "248df4b7-aa70-47b8-a036-33ac447e668d",
                    secret: "secret",
                },
            ],
        };

        server.mockEndpoint().get("/api/webhooks").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.webhooks.list();
        expect(response).toEqual(rawResponseBody);
    });

    test("List (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PolytomicClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {};

        server.mockEndpoint().get("/api/webhooks").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.webhooks.list();
        }).rejects.toThrow(Polytomic.InternalServerError);
    });

    test("Get (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PolytomicClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            data: {
                created_at: "2024-01-01T00:00:00Z",
                disabled: true,
                endpoint: "https://example.com/webhook",
                id: "248df4b7-aa70-47b8-a036-33ac447e668d",
                organization_id: "248df4b7-aa70-47b8-a036-33ac447e668d",
                secret: "secret",
            },
        };

        server
            .mockEndpoint()
            .get("/api/webhooks/248df4b7-aa70-47b8-a036-33ac447e668d")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.webhooks.get("248df4b7-aa70-47b8-a036-33ac447e668d");
        expect(response).toEqual(rawResponseBody);
    });

    test("Get (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PolytomicClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {};

        server.mockEndpoint().get("/api/webhooks/id").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.webhooks.get("id");
        }).rejects.toThrow(Polytomic.NotFoundError);
    });
});
