// This file was auto-generated by Fern from our API Definition.

import * as Polytomic from "../../../src/api/index";
import { PolytomicClient } from "../../../src/Client";
import { mockServerPool } from "../../mock-server/MockServerPool";

describe("PoliciesClient", () => {
    test("List (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PolytomicClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            data: [
                {
                    id: "248df4b7-aa70-47b8-a036-33ac447e668d",
                    name: "Policy",
                    organization_id: "248df4b7-aa70-47b8-a036-33ac447e668d",
                    policy_actions: [{ action: "read", role_ids: ["248df4b7-aa70-47b8-a036-33ac447e668d"] }],
                    system: false,
                },
            ],
        };

        server
            .mockEndpoint()
            .get("/api/permissions/policies")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.permissions.policies.list();
        expect(response).toEqual({
            data: [
                {
                    id: "248df4b7-aa70-47b8-a036-33ac447e668d",
                    name: "Policy",
                    organization_id: "248df4b7-aa70-47b8-a036-33ac447e668d",
                    policy_actions: [
                        {
                            action: "read",
                            role_ids: ["248df4b7-aa70-47b8-a036-33ac447e668d"],
                        },
                    ],
                    system: false,
                },
            ],
        });
    });

    test("List (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PolytomicClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/permissions/policies")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.permissions.policies.list();
        }).rejects.toThrow(Polytomic.UnauthorizedError);
    });

    test("List (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PolytomicClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/permissions/policies")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.permissions.policies.list();
        }).rejects.toThrow(Polytomic.InternalServerError);
    });

    test("Create (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PolytomicClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "Custom" };
        const rawResponseBody = {
            data: {
                id: "248df4b7-aa70-47b8-a036-33ac447e668d",
                name: "Policy",
                organization_id: "248df4b7-aa70-47b8-a036-33ac447e668d",
                policy_actions: [{ action: "read", role_ids: ["248df4b7-aa70-47b8-a036-33ac447e668d"] }],
                system: false,
            },
        };

        server
            .mockEndpoint()
            .post("/api/permissions/policies")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.permissions.policies.create({
            name: "Custom",
        });
        expect(response).toEqual({
            data: {
                id: "248df4b7-aa70-47b8-a036-33ac447e668d",
                name: "Policy",
                organization_id: "248df4b7-aa70-47b8-a036-33ac447e668d",
                policy_actions: [
                    {
                        action: "read",
                        role_ids: ["248df4b7-aa70-47b8-a036-33ac447e668d"],
                    },
                ],
                system: false,
            },
        });
    });

    test("Create (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PolytomicClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/api/permissions/policies")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.permissions.policies.create({
                name: "name",
            });
        }).rejects.toThrow(Polytomic.BadRequestError);
    });

    test("Create (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PolytomicClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/api/permissions/policies")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.permissions.policies.create({
                name: "name",
            });
        }).rejects.toThrow(Polytomic.UnauthorizedError);
    });

    test("Create (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new PolytomicClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/api/permissions/policies")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.permissions.policies.create({
                name: "name",
            });
        }).rejects.toThrow(Polytomic.ForbiddenError);
    });

    test("Create (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new PolytomicClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/api/permissions/policies")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.permissions.policies.create({
                name: "name",
            });
        }).rejects.toThrow(Polytomic.NotFoundError);
    });

    test("Create (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new PolytomicClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/api/permissions/policies")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.permissions.policies.create({
                name: "name",
            });
        }).rejects.toThrow(Polytomic.InternalServerError);
    });

    test("Get (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PolytomicClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            data: {
                id: "248df4b7-aa70-47b8-a036-33ac447e668d",
                name: "Policy",
                organization_id: "248df4b7-aa70-47b8-a036-33ac447e668d",
                policy_actions: [{ action: "read", role_ids: ["248df4b7-aa70-47b8-a036-33ac447e668d"] }],
                system: false,
            },
        };

        server
            .mockEndpoint()
            .get("/api/permissions/policies/248df4b7-aa70-47b8-a036-33ac447e668d")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.permissions.policies.get("248df4b7-aa70-47b8-a036-33ac447e668d");
        expect(response).toEqual({
            data: {
                id: "248df4b7-aa70-47b8-a036-33ac447e668d",
                name: "Policy",
                organization_id: "248df4b7-aa70-47b8-a036-33ac447e668d",
                policy_actions: [
                    {
                        action: "read",
                        role_ids: ["248df4b7-aa70-47b8-a036-33ac447e668d"],
                    },
                ],
                system: false,
            },
        });
    });

    test("Get (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PolytomicClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/permissions/policies/id")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.permissions.policies.get("id");
        }).rejects.toThrow(Polytomic.UnauthorizedError);
    });

    test("Get (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PolytomicClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/permissions/policies/id")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.permissions.policies.get("id");
        }).rejects.toThrow(Polytomic.NotFoundError);
    });

    test("Get (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new PolytomicClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/permissions/policies/id")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.permissions.policies.get("id");
        }).rejects.toThrow(Polytomic.InternalServerError);
    });

    test("Update (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PolytomicClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "Custom" };
        const rawResponseBody = {
            data: {
                id: "248df4b7-aa70-47b8-a036-33ac447e668d",
                name: "Policy",
                organization_id: "248df4b7-aa70-47b8-a036-33ac447e668d",
                policy_actions: [{ action: "read", role_ids: ["248df4b7-aa70-47b8-a036-33ac447e668d"] }],
                system: false,
            },
        };

        server
            .mockEndpoint()
            .put("/api/permissions/policies/248df4b7-aa70-47b8-a036-33ac447e668d")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.permissions.policies.update("248df4b7-aa70-47b8-a036-33ac447e668d", {
            name: "Custom",
        });
        expect(response).toEqual({
            data: {
                id: "248df4b7-aa70-47b8-a036-33ac447e668d",
                name: "Policy",
                organization_id: "248df4b7-aa70-47b8-a036-33ac447e668d",
                policy_actions: [
                    {
                        action: "read",
                        role_ids: ["248df4b7-aa70-47b8-a036-33ac447e668d"],
                    },
                ],
                system: false,
            },
        });
    });

    test("Update (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PolytomicClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .put("/api/permissions/policies/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.permissions.policies.update("id", {
                name: "name",
            });
        }).rejects.toThrow(Polytomic.BadRequestError);
    });

    test("Update (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PolytomicClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .put("/api/permissions/policies/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.permissions.policies.update("id", {
                name: "name",
            });
        }).rejects.toThrow(Polytomic.UnauthorizedError);
    });

    test("Update (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new PolytomicClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .put("/api/permissions/policies/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.permissions.policies.update("id", {
                name: "name",
            });
        }).rejects.toThrow(Polytomic.ForbiddenError);
    });

    test("Update (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new PolytomicClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .put("/api/permissions/policies/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.permissions.policies.update("id", {
                name: "name",
            });
        }).rejects.toThrow(Polytomic.NotFoundError);
    });

    test("Update (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new PolytomicClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .put("/api/permissions/policies/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.permissions.policies.update("id", {
                name: "name",
            });
        }).rejects.toThrow(Polytomic.InternalServerError);
    });

    test("Remove (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PolytomicClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        server
            .mockEndpoint()
            .delete("/api/permissions/policies/248df4b7-aa70-47b8-a036-33ac447e668d")
            .respondWith()
            .statusCode(200)
            .build();

        const response = await client.permissions.policies.remove("248df4b7-aa70-47b8-a036-33ac447e668d");
        expect(response).toEqual(undefined);
    });

    test("Remove (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PolytomicClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .delete("/api/permissions/policies/id")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.permissions.policies.remove("id");
        }).rejects.toThrow(Polytomic.UnauthorizedError);
    });

    test("Remove (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PolytomicClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .delete("/api/permissions/policies/id")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.permissions.policies.remove("id");
        }).rejects.toThrow(Polytomic.ForbiddenError);
    });

    test("Remove (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new PolytomicClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .delete("/api/permissions/policies/id")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.permissions.policies.remove("id");
        }).rejects.toThrow(Polytomic.NotFoundError);
    });

    test("Remove (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new PolytomicClient({
            maxRetries: 0,
            token: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .delete("/api/permissions/policies/id")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.permissions.policies.remove("id");
        }).rejects.toThrow(Polytomic.InternalServerError);
    });
});
