/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../environments";
import * as core from "../../../../core";
import * as Polytomic from "../../../index";
import { toJson } from "../../../../core/json";
import urlJoin from "url-join";
import * as errors from "../../../../errors/index";

export declare namespace QueryRunner {
    export interface Options {
        environment?: core.Supplier<environments.PolytomicEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        token: core.Supplier<core.BearerToken>;
        /** Override the X-Polytomic-Version header */
        version?: core.Supplier<unknown>;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Override the X-Polytomic-Version header */
        version?: unknown;
        /** Additional headers to include in the request. */
        headers?: Record<string, string>;
    }
}

export class QueryRunner {
    constructor(protected readonly _options: QueryRunner.Options) {}

    /**
     * Submit a query for asynchronous execution against the connection. The initial response may only contain the query task id and status. Poll GET /api/queries/{id} with the returned id to retrieve completion status, fields, and results.
     *
     * @param {string} connectionId
     * @param {Polytomic.V4RunQueryRequest} request
     * @param {QueryRunner.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Polytomic.BadRequestError}
     * @throws {@link Polytomic.UnauthorizedError}
     * @throws {@link Polytomic.NotFoundError}
     * @throws {@link Polytomic.InternalServerError}
     *
     * @example
     *     await client.queryRunner.runQuery("248df4b7-aa70-47b8-a036-33ac447e668d", {
     *         query: "SELECT * FROM table"
     *     })
     */
    public runQuery(
        connectionId: string,
        request: Polytomic.V4RunQueryRequest = {},
        requestOptions?: QueryRunner.RequestOptions,
    ): core.HttpResponsePromise<Polytomic.V4RunQueryEnvelope> {
        return core.HttpResponsePromise.fromPromise(this.__runQuery(connectionId, request, requestOptions));
    }

    private async __runQuery(
        connectionId: string,
        request: Polytomic.V4RunQueryRequest = {},
        requestOptions?: QueryRunner.RequestOptions,
    ): Promise<core.WithRawResponse<Polytomic.V4RunQueryEnvelope>> {
        const { query, ..._body } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (query != null) {
            _queryParams["query"] = query;
        }

        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PolytomicEnvironment.Default,
                `api/connections/${encodeURIComponent(connectionId)}/query`,
            ),
            method: "POST",
            headers: {
                Authorization: await this._getAuthorizationHeader(),
                "X-Polytomic-Version":
                    typeof (await core.Supplier.get(this._options.version)) === "string"
                        ? await core.Supplier.get(this._options.version)
                        : toJson(await core.Supplier.get(this._options.version)),
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "",
                "X-Fern-SDK-Version": "1.16.2",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            queryParameters: _queryParams,
            requestType: "json",
            body: _body,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as Polytomic.V4RunQueryEnvelope, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Polytomic.BadRequestError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                case 401:
                    throw new Polytomic.UnauthorizedError(
                        _response.error.body as Polytomic.RestErrResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Polytomic.NotFoundError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Polytomic.InternalServerError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.PolytomicError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.PolytomicError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.PolytomicTimeoutError(
                    "Timeout exceeded when calling POST /api/connections/{connection_id}/query.",
                );
            case "unknown":
                throw new errors.PolytomicError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Fetch the latest status for a submitted query and, once complete, return fields and paginated results. Use the query id returned by POST /api/connections/{connection_id}/query.
     *
     * @param {string} id
     * @param {Polytomic.QueryRunnerGetQueryRequest} request
     * @param {QueryRunner.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Polytomic.BadRequestError}
     * @throws {@link Polytomic.UnauthorizedError}
     * @throws {@link Polytomic.NotFoundError}
     * @throws {@link Polytomic.InternalServerError}
     *
     * @example
     *     await client.queryRunner.getQuery("248df4b7-aa70-47b8-a036-33ac447e668d")
     */
    public getQuery(
        id: string,
        request: Polytomic.QueryRunnerGetQueryRequest = {},
        requestOptions?: QueryRunner.RequestOptions,
    ): core.HttpResponsePromise<Polytomic.V4QueryResultsEnvelope> {
        return core.HttpResponsePromise.fromPromise(this.__getQuery(id, request, requestOptions));
    }

    private async __getQuery(
        id: string,
        request: Polytomic.QueryRunnerGetQueryRequest = {},
        requestOptions?: QueryRunner.RequestOptions,
    ): Promise<core.WithRawResponse<Polytomic.V4QueryResultsEnvelope>> {
        const { page } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (page != null) {
            _queryParams["page"] = page;
        }

        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PolytomicEnvironment.Default,
                `api/queries/${encodeURIComponent(id)}`,
            ),
            method: "GET",
            headers: {
                Authorization: await this._getAuthorizationHeader(),
                "X-Polytomic-Version":
                    typeof (await core.Supplier.get(this._options.version)) === "string"
                        ? await core.Supplier.get(this._options.version)
                        : toJson(await core.Supplier.get(this._options.version)),
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "",
                "X-Fern-SDK-Version": "1.16.2",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            queryParameters: _queryParams,
            requestType: "json",
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as Polytomic.V4QueryResultsEnvelope, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Polytomic.BadRequestError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                case 401:
                    throw new Polytomic.UnauthorizedError(
                        _response.error.body as Polytomic.RestErrResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Polytomic.NotFoundError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Polytomic.InternalServerError(
                        _response.error.body as Polytomic.ApiError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.PolytomicError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.PolytomicError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.PolytomicTimeoutError("Timeout exceeded when calling GET /api/queries/{id}.");
            case "unknown":
                throw new errors.PolytomicError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    protected async _getAuthorizationHeader(): Promise<string> {
        return `Bearer ${await core.Supplier.get(this._options.token)}`;
    }
}
